/**
 * Phase 11: Reporting & Export
 *
 * Tests UC-063 through UC-067 against the real database.
 * Requires local Supabase running with seed data.
 *
 * @see docs/use-cases/11-reporting.md
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest"
import { createAdminCaller, prisma, SEED } from "../helpers"

type Caller = Awaited<ReturnType<typeof createAdminCaller>>

/** Seed account IDs from supabase/seed.sql */
const SEED_ACCOUNT_ID_1 = "00000000-0000-0000-0000-000000001101" // NIGHT
const SEED_ACCOUNT_ID_2 = "00000000-0000-0000-0000-000000001102" // SAT

describe("Phase 11: Reporting & Export", () => {
  let caller: Caller

  // Track created record IDs for cleanup
  const created = {
    reportIds: [] as string[],
    payrollExportIds: [] as string[],
    exportInterfaceIds: [] as string[],
    monthlyEvalTemplateIds: [] as string[],
  }

  // Shared state for cross-test references
  const state: Record<string, string> = {}

  beforeAll(async () => {
    caller = await createAdminCaller()

    // Clean up leftover test data from previous runs
    await prisma.report
      .deleteMany({
        where: {
          tenantId: SEED.TENANT_ID,
          name: { startsWith: "E2E" },
        },
      })
      .catch(() => {})

    await prisma.payrollExport
      .deleteMany({
        where: {
          tenantId: SEED.TENANT_ID,
          createdBy: SEED.ADMIN_USER_ID,
          // Only clean up exports generated by E2E in a safe date range
          year: 2025,
          month: 1,
        },
      })
      .catch(() => {})

    // Clean up export interface accounts before interfaces
    await prisma.exportInterfaceAccount
      .deleteMany({
        where: {
          exportInterface: {
            tenantId: SEED.TENANT_ID,
            name: { startsWith: "E2E" },
          },
        },
      })
      .catch(() => {})

    await prisma.exportInterface
      .deleteMany({
        where: {
          tenantId: SEED.TENANT_ID,
          name: { startsWith: "E2E" },
        },
      })
      .catch(() => {})

    await prisma.monthlyEvaluationTemplate
      .deleteMany({
        where: {
          tenantId: SEED.TENANT_ID,
          name: { startsWith: "E2E" },
        },
      })
      .catch(() => {})
  })

  afterAll(async () => {
    // Cleanup in reverse dependency order

    if (created.reportIds.length > 0) {
      await prisma.report
        .deleteMany({
          where: { id: { in: created.reportIds } },
        })
        .catch(() => {})
    }

    if (created.payrollExportIds.length > 0) {
      await prisma.payrollExport
        .deleteMany({
          where: { id: { in: created.payrollExportIds } },
        })
        .catch(() => {})
    }

    if (created.exportInterfaceIds.length > 0) {
      await prisma.exportInterfaceAccount
        .deleteMany({
          where: {
            exportInterfaceId: { in: created.exportInterfaceIds },
          },
        })
        .catch(() => {})
      await prisma.exportInterface
        .deleteMany({
          where: { id: { in: created.exportInterfaceIds } },
        })
        .catch(() => {})
    }

    if (created.monthlyEvalTemplateIds.length > 0) {
      await prisma.monthlyEvaluationTemplate
        .deleteMany({
          where: { id: { in: created.monthlyEvalTemplateIds } },
        })
        .catch(() => {})
    }
  })

  // =========================================================
  // UC-063: Report generieren
  // =========================================================
  describe("UC-063: Report generieren", () => {
    it("should generate a monthly overview report (CSV)", async () => {
      const result = await caller.reports.generate({
        reportType: "monthly_overview",
        format: "csv",
        name: "E2E Monthly Overview Jan 2026",
        parameters: {
          fromDate: "2026-01-01",
          toDate: "2026-01-31",
        },
      })

      expect(result.id).toBeDefined()
      expect(result.reportType).toBe("monthly_overview")
      expect(result.format).toBe("csv")
      expect(result.name).toBe("E2E Monthly Overview Jan 2026")
      expect(result.status).toBe("completed")
      expect(result.createdBy).toBe(SEED.ADMIN_USER_ID)
      state.reportId = result.id
      created.reportIds.push(result.id)
    })

    it("should generate an overtime report (JSON)", async () => {
      const result = await caller.reports.generate({
        reportType: "overtime_report",
        format: "json",
        name: "E2E Overtime Report",
        parameters: {
          fromDate: "2026-01-01",
          toDate: "2026-01-31",
        },
      })

      expect(result.id).toBeDefined()
      expect(result.reportType).toBe("overtime_report")
      expect(result.format).toBe("json")
      expect(result.status).toBe("completed")
      state.jsonReportId = result.id
      created.reportIds.push(result.id)
    })

    it("should generate a vacation report", async () => {
      const result = await caller.reports.generate({
        reportType: "vacation_report",
        format: "csv",
        name: "E2E Vacation Report",
        parameters: {
          fromDate: "2026-01-01",
          toDate: "2026-12-31",
        },
      })

      expect(result.id).toBeDefined()
      expect(result.status).toBe("completed")
      created.reportIds.push(result.id)
    })

    it("should generate a department summary report", async () => {
      const result = await caller.reports.generate({
        reportType: "department_summary",
        format: "csv",
        name: "E2E Department Summary",
        parameters: {
          fromDate: "2026-01-01",
          toDate: "2026-01-31",
        },
      })

      expect(result.id).toBeDefined()
      expect(result.status).toBe("completed")
      created.reportIds.push(result.id)
    })

    it("should list reports with cursor-based pagination", async () => {
      const result = await caller.reports.list()
      expect(result.data.length).toBeGreaterThanOrEqual(1)
      expect(result.meta).toBeDefined()
      expect(typeof result.meta.hasMore).toBe("boolean")
    })

    it("should filter reports by type", async () => {
      const result = await caller.reports.list({
        reportType: "monthly_overview",
      })
      expect(result.data.length).toBeGreaterThanOrEqual(1)
      result.data.forEach((r: any) => {
        expect(r.reportType).toBe("monthly_overview")
      })
    })

    it("should filter reports by status", async () => {
      const result = await caller.reports.list({
        status: "completed",
      })
      expect(result.data.length).toBeGreaterThanOrEqual(1)
      result.data.forEach((r: any) => {
        expect(r.status).toBe("completed")
      })
    })

    it("should retrieve a report by ID", async () => {
      const result = await caller.reports.getById({ id: state.reportId! })
      expect(result.id).toBe(state.reportId!)
      expect(result.name).toBe("E2E Monthly Overview Jan 2026")
      expect(result.status).toBe("completed")
    })
  })

  // =========================================================
  // UC-064: Report herunterladen
  // =========================================================
  describe("UC-064: Report herunterladen", () => {
    it("should download a CSV report", async () => {
      const result = await caller.reports.download({ id: state.reportId! })

      expect(result.content).toBeDefined()
      expect(result.content.length).toBeGreaterThan(0)
      expect(result.contentType).toBeDefined()
      expect(result.filename).toBeDefined()
    })

    it("should download a JSON report", async () => {
      const result = await caller.reports.download({
        id: state.jsonReportId!,
      })

      expect(result.content).toBeDefined()
      expect(result.content.length).toBeGreaterThan(0)
      expect(result.filename).toBeDefined()
    })

    it("should reject download for non-existent report", async () => {
      await expect(
        caller.reports.download({
          id: "00000000-0000-0000-0000-000000099999",
        })
      ).rejects.toThrow()
    })

    it("should delete a report", async () => {
      // Create a temporary report to delete
      const temp = await caller.reports.generate({
        reportType: "absence_report",
        format: "csv",
        name: "E2E Temp Report To Delete",
        parameters: {
          fromDate: "2026-01-01",
          toDate: "2026-01-31",
        },
      })

      const result = await caller.reports.delete({ id: temp.id })
      expect(result.success).toBe(true)

      // Verify it is gone
      await expect(
        caller.reports.getById({ id: temp.id })
      ).rejects.toThrow()
    })
  })

  // =========================================================
  // UC-065: Export-Schnittstelle konfigurieren
  // =========================================================
  describe("UC-065: Export-Schnittstelle konfigurieren", () => {
    it("should create an export interface", async () => {
      const result = await caller.exportInterfaces.create({
        interfaceNumber: 900,
        name: "E2E DATEV Export",
        mandantNumber: "E2E-12345",
        exportPath: "/tmp/e2e-exports",
        outputFilename: "e2e_payroll_{year}_{month}.csv",
      })

      expect(result.id).toBeDefined()
      expect(result.interfaceNumber).toBe(900)
      expect(result.name).toBe("E2E DATEV Export")
      expect(result.mandantNumber).toBe("E2E-12345")
      expect(result.isActive).toBe(true)
      expect(result.accounts).toEqual([])
      state.exportInterfaceId = result.id
      created.exportInterfaceIds.push(result.id)
    })

    it("should create a second export interface", async () => {
      const result = await caller.exportInterfaces.create({
        interfaceNumber: 901,
        name: "E2E Sage Export",
      })

      expect(result.id).toBeDefined()
      state.exportInterface2Id = result.id
      created.exportInterfaceIds.push(result.id)
    })

    it("should reject duplicate interface numbers", async () => {
      await expect(
        caller.exportInterfaces.create({
          interfaceNumber: 900,
          name: "E2E Duplicate Interface",
        })
      ).rejects.toThrow()
    })

    it("should list export interfaces", async () => {
      const { data } = await caller.exportInterfaces.list()
      const names = data.map((i: any) => i.name)
      expect(names).toContain("E2E DATEV Export")
      expect(names).toContain("E2E Sage Export")
    })

    it("should retrieve an export interface by ID", async () => {
      const result = await caller.exportInterfaces.getById({
        id: state.exportInterfaceId!,
      })
      expect(result.id).toBe(state.exportInterfaceId!)
      expect(result.name).toBe("E2E DATEV Export")
    })

    it("should set accounts on an export interface", async () => {
      const { data } = await caller.exportInterfaces.setAccounts({
        id: state.exportInterfaceId!,
        accountIds: [SEED_ACCOUNT_ID_1, SEED_ACCOUNT_ID_2],
      })

      expect(data.length).toBe(2)
      expect(data[0]!.sortOrder).toBe(0)
      expect(data[1]!.sortOrder).toBe(1)
      expect(data[0]!.account).toBeDefined()
    })

    it("should list accounts for an export interface", async () => {
      const { data } = await caller.exportInterfaces.listAccounts({
        id: state.exportInterfaceId!,
      })

      expect(data.length).toBe(2)
      const accountIds = data.map((a: any) => a.accountId)
      expect(accountIds).toContain(SEED_ACCOUNT_ID_1)
      expect(accountIds).toContain(SEED_ACCOUNT_ID_2)
    })

    it("should update an export interface", async () => {
      const result = await caller.exportInterfaces.update({
        id: state.exportInterfaceId!,
        name: "E2E DATEV Export Updated",
        mandantNumber: "E2E-99999",
      })

      expect(result.name).toBe("E2E DATEV Export Updated")
      expect(result.mandantNumber).toBe("E2E-99999")
    })

    it("should replace accounts on an export interface", async () => {
      const { data } = await caller.exportInterfaces.setAccounts({
        id: state.exportInterfaceId!,
        accountIds: [SEED_ACCOUNT_ID_2], // Only one account now
      })

      expect(data.length).toBe(1)
      expect(data[0]!.accountId).toBe(SEED_ACCOUNT_ID_2)
    })

    it("should delete an unused export interface", async () => {
      const result = await caller.exportInterfaces.delete({
        id: state.exportInterface2Id!,
      })
      expect(result.success).toBe(true)

      // Remove from cleanup list
      created.exportInterfaceIds = created.exportInterfaceIds.filter(
        (id) => id !== state.exportInterface2Id!
      )
    })
  })

  // =========================================================
  // UC-066: Lohnexport generieren und herunterladen
  // =========================================================
  describe("UC-066: Lohnexport generieren und herunterladen", () => {
    it("should generate a payroll export for a past month", async () => {
      const result = await caller.payrollExports.generate({
        year: 2025,
        month: 1,
        format: "csv",
        exportType: "standard",
      })

      expect(result.id).toBeDefined()
      expect(result.year).toBe(2025)
      expect(result.month).toBe(1)
      expect(result.format).toBe("csv")
      expect(result.exportType).toBe("standard")
      expect(result.status).toBe("completed")
      expect(result.createdBy).toBe(SEED.ADMIN_USER_ID)
      state.payrollExportId = result.id
      created.payrollExportIds.push(result.id)
    })

    it("should generate a payroll export with export interface", async () => {
      const result = await caller.payrollExports.generate({
        year: 2025,
        month: 2,
        format: "csv",
        exportType: "standard",
        exportInterfaceId: state.exportInterfaceId!,
      })

      expect(result.id).toBeDefined()
      expect(result.exportInterfaceId).toBe(state.exportInterfaceId!)
      expect(result.status).toBe("completed")
      state.payrollExport2Id = result.id
      created.payrollExportIds.push(result.id)
    })

    it("should list payroll exports", async () => {
      const result = await caller.payrollExports.list()
      expect(result.data.length).toBeGreaterThanOrEqual(1)
      expect(result.meta).toBeDefined()
    })

    it("should filter payroll exports by year and month", async () => {
      const result = await caller.payrollExports.list({
        year: 2025,
        month: 1,
      })
      expect(result.data.length).toBeGreaterThanOrEqual(1)
      result.data.forEach((e: any) => {
        expect(e.year).toBe(2025)
        expect(e.month).toBe(1)
      })
    })

    it("should retrieve a payroll export by ID", async () => {
      const result = await caller.payrollExports.getById({
        id: state.payrollExportId!,
      })
      expect(result.id).toBe(state.payrollExportId!)
      expect(result.year).toBe(2025)
      expect(result.month).toBe(1)
    })

    it("should download a payroll export", async () => {
      const result = await caller.payrollExports.download({
        id: state.payrollExportId!,
      })

      expect(result.content).toBeDefined()
      expect(result.content.length).toBeGreaterThan(0)
      expect(result.contentType).toBeDefined()
      expect(result.filename).toBeDefined()
    })

    it("should preview a payroll export", async () => {
      const result = await caller.payrollExports.preview({
        id: state.payrollExportId!,
      })

      expect(result.lines).toBeDefined()
      expect(result.summary).toBeDefined()
      expect(typeof result.summary.employeeCount).toBe("number")
      expect(typeof result.summary.totalHours).toBe("number")
      expect(typeof result.summary.totalOvertime).toBe("number")
    })

    it("should delete a payroll export", async () => {
      const result = await caller.payrollExports.delete({
        id: state.payrollExport2Id!,
      })
      expect(result.success).toBe(true)

      // Remove from cleanup list
      created.payrollExportIds = created.payrollExportIds.filter(
        (id) => id !== state.payrollExport2Id!
      )
    })

    it("should reject deleting export interface that has been used", async () => {
      // First generate a payroll export using the interface
      // The interface already has a generated export (payrollExport2 was deleted,
      // but let's create one that stays)
      const exportForInterfaceTest = await caller.payrollExports.generate({
        year: 2025,
        month: 3,
        format: "csv",
        exportType: "standard",
        exportInterfaceId: state.exportInterfaceId!,
      })
      created.payrollExportIds.push(exportForInterfaceTest.id)

      // Now trying to delete the interface should fail
      await expect(
        caller.exportInterfaces.delete({ id: state.exportInterfaceId! })
      ).rejects.toThrow()
    })
  })

  // =========================================================
  // UC-067: Monatsauswertungs-Template anpassen
  // =========================================================
  describe("UC-067: Monatsauswertungs-Template anpassen", () => {
    it("should create a monthly evaluation template", async () => {
      const result = await caller.monthlyEvalTemplates.create({
        name: "E2E Standard Template",
        description: "Standard monthly evaluation",
        flextimeCapPositive: 40,
        flextimeCapNegative: 20,
        overtimeThreshold: 10,
        maxCarryoverVacation: 5,
        isDefault: false,
      })

      expect(result.id).toBeDefined()
      expect(result.name).toBe("E2E Standard Template")
      expect(result.flextimeCapPositive).toBe(40)
      expect(result.flextimeCapNegative).toBe(20)
      expect(result.overtimeThreshold).toBe(10)
      expect(result.maxCarryoverVacation).toBe(5)
      expect(result.isDefault).toBe(false)
      expect(result.isActive).toBe(true)
      state.templateId = result.id
      created.monthlyEvalTemplateIds.push(result.id)
    })

    it("should create a second template", async () => {
      const result = await caller.monthlyEvalTemplates.create({
        name: "E2E Extended Template",
        description: "Extended with higher caps",
        flextimeCapPositive: 60,
        flextimeCapNegative: 30,
        overtimeThreshold: 20,
        maxCarryoverVacation: 10,
      })

      expect(result.id).toBeDefined()
      state.template2Id = result.id
      created.monthlyEvalTemplateIds.push(result.id)
    })

    it("should list monthly evaluation templates", async () => {
      const { data } = await caller.monthlyEvalTemplates.list()
      expect(data.length).toBeGreaterThanOrEqual(2)
      const names = data.map((t: any) => t.name)
      expect(names).toContain("E2E Standard Template")
      expect(names).toContain("E2E Extended Template")
    })

    it("should filter templates by active status", async () => {
      const { data } = await caller.monthlyEvalTemplates.list({
        isActive: true,
      })
      expect(data.length).toBeGreaterThanOrEqual(2)
    })

    it("should retrieve a template by ID", async () => {
      const result = await caller.monthlyEvalTemplates.getById({
        id: state.templateId!,
      })
      expect(result.id).toBe(state.templateId!)
      expect(result.name).toBe("E2E Standard Template")
    })

    it("should update a template", async () => {
      const result = await caller.monthlyEvalTemplates.update({
        id: state.templateId!,
        name: "E2E Standard Template Updated",
        flextimeCapPositive: 50,
      })

      expect(result.name).toBe("E2E Standard Template Updated")
      expect(result.flextimeCapPositive).toBe(50)
      // Other fields remain unchanged
      expect(result.flextimeCapNegative).toBe(20)
    })

    it("should set a template as default", async () => {
      const result = await caller.monthlyEvalTemplates.setDefault({
        id: state.templateId!,
      })

      expect(result.isDefault).toBe(true)
    })

    it("should retrieve the default template", async () => {
      const result = await caller.monthlyEvalTemplates.getDefault()

      expect(result).toBeDefined()
      expect(result.isDefault).toBe(true)
    })

    it("should switch default to another template", async () => {
      const result = await caller.monthlyEvalTemplates.setDefault({
        id: state.template2Id!,
      })

      expect(result.isDefault).toBe(true)
      expect(result.id).toBe(state.template2Id!)

      // Previous default should no longer be default
      const previous = await caller.monthlyEvalTemplates.getById({
        id: state.templateId!,
      })
      expect(previous.isDefault).toBe(false)
    })

    it("should not delete the default template", async () => {
      await expect(
        caller.monthlyEvalTemplates.delete({ id: state.template2Id! })
      ).rejects.toThrow()
    })

    it("should delete a non-default template", async () => {
      const result = await caller.monthlyEvalTemplates.delete({
        id: state.templateId!,
      })
      expect(result.success).toBe(true)

      // Remove from cleanup list
      created.monthlyEvalTemplateIds =
        created.monthlyEvalTemplateIds.filter(
          (id) => id !== state.templateId!
        )
    })
  })
})
