/**
 * Tests for bookings router — closed-month guard.
 *
 * Verifies that create/update/delete mutations are blocked when the
 * target month is closed (MonthlyValue.isClosed === true), and allowed
 * when the month is open or has no MonthlyValue record.
 */
import { describe, it, expect, vi } from "vitest"
import { TRPCError } from "@trpc/server"
import { createCallerFactory } from "@/trpc/init"
import { bookingsRouter } from "../bookings"
import {
  createMockContext,
  createMockSession,
  createMockUserTenant,
  createUserWithPermissions,
} from "./helpers"
import { permissionIdByKey } from "@/lib/auth/permission-catalog"

// --- Constants ---

const TENANT_ID = "a0000000-0000-4000-a000-000000000100"
const USER_ID = "a0000000-0000-4000-a000-000000000001"
const EMPLOYEE_ID = "a0000000-0000-4000-a000-000000000002"
const BOOKING_ID = "a0000000-0000-4000-a000-000000000003"
const BOOKING_TYPE_ID = "a0000000-0000-4000-a000-000000000004"
const DEPT_ID = "a0000000-0000-4000-a000-000000000005"

const EDIT_PERM = permissionIdByKey("time_tracking.edit")!
const DELETE_PERM = permissionIdByKey("booking_overview.delete_bookings")!
const VIEW_ALL_PERM = permissionIdByKey("time_tracking.view_all")!

const createCaller = createCallerFactory(bookingsRouter)

// --- Helpers ---

function makeBookingRecord(overrides: Record<string, unknown> = {}) {
  return {
    id: BOOKING_ID,
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    bookingDate: new Date("2026-01-15T00:00:00Z"),
    bookingTypeId: BOOKING_TYPE_ID,
    originalTime: 480,
    editedTime: 480,
    calculatedTime: null,
    pairId: null,
    source: "web",
    terminalId: null,
    notes: null,
    bookingReasonId: null,
    isAutoGenerated: false,
    originalBookingId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: USER_ID,
    updatedBy: USER_ID,
    bookingType: {
      id: BOOKING_TYPE_ID,
      code: "COME",
      name: "Kommen",
      direction: "in",
    },
    bookingReason: null,
    employee: {
      id: EMPLOYEE_ID,
      personnelNumber: "EMP001",
      firstName: "Max",
      lastName: "Mustermann",
      departmentId: DEPT_ID,
    },
    ...overrides,
  }
}

function makeClosedMonthlyValue() {
  return {
    id: "mv-closed",
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    year: 2026,
    month: 1,
    isClosed: true,
    closedAt: new Date(),
    closedBy: USER_ID,
  }
}

function makeOpenMonthlyValue() {
  return {
    id: "mv-open",
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    year: 2026,
    month: 1,
    isClosed: false,
    closedAt: null,
    closedBy: null,
  }
}

function createTestContext(prisma: Record<string, unknown>) {
  return createMockContext({
    prisma: prisma as unknown as ReturnType<typeof createMockContext>["prisma"],
    authToken: "test-token",
    user: createUserWithPermissions([EDIT_PERM, DELETE_PERM, VIEW_ALL_PERM], {
      id: USER_ID,
      dataScopeType: "all",
      userTenants: [createMockUserTenant(USER_ID, TENANT_ID)],
    }),
    session: createMockSession(),
    tenantId: TENANT_ID,
  })
}

// --- Tests ---

describe("bookings — closed-month guard", () => {
  // ── CREATE ──

  describe("create", () => {
    it("blocks creation when month is closed", async () => {
      const booking = makeBookingRecord()
      const mockPrisma = {
        employee: {
          findFirst: vi.fn().mockResolvedValue({
            id: EMPLOYEE_ID,
            tenantId: TENANT_ID,
            departmentId: DEPT_ID,
          }),
        },
        bookingType: {
          findFirst: vi.fn().mockResolvedValue({
            id: BOOKING_TYPE_ID,
            code: "COME",
            name: "Kommen",
            direction: "in",
            isActive: true,
          }),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeClosedMonthlyValue()),
        },
        booking: {
          create: vi.fn().mockResolvedValue(booking),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      await expect(
        caller.create({
          employeeId: EMPLOYEE_ID,
          bookingTypeId: BOOKING_TYPE_ID,
          bookingDate: "2026-01-15",
          time: "08:00",
        })
      ).rejects.toThrow(TRPCError)

      await expect(
        caller.create({
          employeeId: EMPLOYEE_ID,
          bookingTypeId: BOOKING_TYPE_ID,
          bookingDate: "2026-01-15",
          time: "08:00",
        })
      ).rejects.toMatchObject({ code: "CONFLICT" })

      // booking.create should NOT have been called
      expect(mockPrisma.booking.create).not.toHaveBeenCalled()
    })

    it("allows creation when month is open", async () => {
      const booking = makeBookingRecord()
      const mockPrisma = {
        employee: {
          findFirst: vi.fn().mockResolvedValue({
            id: EMPLOYEE_ID,
            tenantId: TENANT_ID,
            departmentId: DEPT_ID,
          }),
        },
        bookingType: {
          findFirst: vi.fn().mockResolvedValue({
            id: BOOKING_TYPE_ID,
            code: "COME",
            name: "Kommen",
            direction: "in",
            isActive: true,
          }),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeOpenMonthlyValue()),
        },
        booking: {
          create: vi.fn().mockResolvedValue(booking),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      const result = await caller.create({
        employeeId: EMPLOYEE_ID,
        bookingTypeId: BOOKING_TYPE_ID,
        bookingDate: "2026-01-15",
        time: "08:00",
      })

      expect(result.id).toBe(BOOKING_ID)
      expect(mockPrisma.booking.create).toHaveBeenCalled()
    })

    it("allows creation when no MonthlyValue record exists", async () => {
      const booking = makeBookingRecord()
      const mockPrisma = {
        employee: {
          findFirst: vi.fn().mockResolvedValue({
            id: EMPLOYEE_ID,
            tenantId: TENANT_ID,
            departmentId: DEPT_ID,
          }),
        },
        bookingType: {
          findFirst: vi.fn().mockResolvedValue({
            id: BOOKING_TYPE_ID,
            code: "COME",
            name: "Kommen",
            direction: "in",
            isActive: true,
          }),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(null),
        },
        booking: {
          create: vi.fn().mockResolvedValue(booking),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      const result = await caller.create({
        employeeId: EMPLOYEE_ID,
        bookingTypeId: BOOKING_TYPE_ID,
        bookingDate: "2026-01-15",
        time: "08:00",
      })

      expect(result.id).toBe(BOOKING_ID)
    })
  })

  // ── UPDATE ──

  describe("update", () => {
    it("blocks update when month is closed", async () => {
      const existing = makeBookingRecord()
      const mockPrisma = {
        booking: {
          findFirst: vi.fn().mockResolvedValue(existing),
          updateMany: vi.fn().mockResolvedValue({ count: 1 }),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeClosedMonthlyValue()),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      await expect(
        caller.update({ id: BOOKING_ID, time: "09:00" })
      ).rejects.toMatchObject({ code: "CONFLICT" })

      expect(mockPrisma.booking.updateMany).not.toHaveBeenCalled()
    })

    it("allows update when month is open", async () => {
      const existing = makeBookingRecord()
      const updated = makeBookingRecord({ editedTime: 540 })
      const mockPrisma = {
        booking: {
          findFirst: vi.fn()
            .mockResolvedValueOnce(existing)
            .mockResolvedValueOnce(updated),
          updateMany: vi.fn().mockResolvedValue({ count: 1 }),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeOpenMonthlyValue()),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      const result = await caller.update({ id: BOOKING_ID, time: "09:00" })

      expect(result.editedTime).toBe(540)
      expect(mockPrisma.booking.updateMany).toHaveBeenCalled()
    })
  })

  // ── DELETE ──

  describe("delete", () => {
    it("blocks delete when month is closed", async () => {
      const existing = makeBookingRecord()
      const mockPrisma = {
        booking: {
          findFirst: vi.fn().mockResolvedValue(existing),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeClosedMonthlyValue()),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      await expect(
        caller.delete({ id: BOOKING_ID })
      ).rejects.toMatchObject({ code: "CONFLICT" })
    })

    it("allows delete when month is open", async () => {
      const existing = makeBookingRecord()
      const mockPrisma = {
        booking: {
          findFirst: vi.fn().mockResolvedValue(existing),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeOpenMonthlyValue()),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      const result = await caller.delete({ id: BOOKING_ID })

      expect(result.success).toBe(true)
    })
  })

  // ── ERROR MESSAGE ──

  describe("error message", () => {
    it("includes month/year in the error message", async () => {
      const existing = makeBookingRecord()
      const mockPrisma = {
        booking: {
          findFirst: vi.fn().mockResolvedValue(existing),
        },
        monthlyValue: {
          findFirst: vi.fn().mockResolvedValue(makeClosedMonthlyValue()),
        },
      }

      const caller = createCaller(createTestContext(mockPrisma))
      try {
        await caller.update({ id: BOOKING_ID, time: "09:00" })
        expect.fail("Should have thrown")
      } catch (err) {
        expect(err).toBeInstanceOf(TRPCError)
        expect((err as TRPCError).message).toContain("01/2026")
        expect((err as TRPCError).message).toContain("abgeschlossen")
      }
    })
  })
})
