/**
 * Bookings Router
 *
 * Provides booking CRUD operations via tRPC procedures.
 * Includes paginated list with filters, data scope enforcement,
 * and derived booking creation.
 *
 * Replaces the Go backend booking endpoints:
 * - GET /bookings -> bookings.list
 * - GET /bookings/{id} -> bookings.getById
 * - POST /bookings -> bookings.create
 * - PUT /bookings/{id} -> bookings.update
 * - DELETE /bookings/{id} -> bookings.delete
 *
 * Recalculation triggers: After each mutation (create/update/delete),
 * DailyCalcService.calculateDay() is called to recalculate the affected day.
 * @see ZMI-TICKET-235
 *
 * @see apps/api/internal/service/booking.go
 * @see apps/api/internal/handler/booking.go
 * @see apps/api/internal/repository/booking.go
 */
import { z } from "zod"
import { createTRPCRouter, tenantProcedure } from "@/trpc/init"
import {
  requirePermission,
  applyDataScope,
  type DataScope,
} from "@/lib/auth/middleware"
import { permissionIdByKey } from "@/lib/auth/permission-catalog"
import { handleServiceError } from "@/trpc/errors"
import * as bookingsService from "@/lib/services/bookings-service"

// --- Permission Constants ---
// Matching Go route registration at apps/api/internal/handler/routes.go:401-465

const VIEW_OWN = permissionIdByKey("time_tracking.view_own")!
const VIEW_ALL = permissionIdByKey("time_tracking.view_all")!
const EDIT = permissionIdByKey("time_tracking.edit")!
const DELETE_BOOKINGS = permissionIdByKey("booking_overview.delete_bookings")!

// --- Output Schemas ---

const bookingTypeSummarySchema = z
  .object({
    id: z.string(),
    code: z.string(),
    name: z.string(),
    direction: z.string(),
  })
  .nullable()

const bookingReasonSummarySchema = z
  .object({
    id: z.string(),
    code: z.string(),
    label: z.string(),
  })
  .nullable()

const employeeSummarySchema = z
  .object({
    id: z.string(),
    personnelNumber: z.string(),
    firstName: z.string(),
    lastName: z.string(),
    departmentId: z.string().nullable(),
  })
  .nullable()

const bookingOutputSchema = z.object({
  id: z.string(),
  tenantId: z.string(),
  employeeId: z.string(),
  bookingDate: z.date(),
  bookingTypeId: z.string(),
  originalTime: z.number().int(),
  editedTime: z.number().int(),
  calculatedTime: z.number().int().nullable(),
  pairId: z.string().nullable(),
  source: z.string().nullable(),
  terminalId: z.string().nullable(),
  notes: z.string().nullable(),
  bookingReasonId: z.string().nullable(),
  isAutoGenerated: z.boolean(),
  originalBookingId: z.string().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
  createdBy: z.string().nullable(),
  updatedBy: z.string().nullable(),
  // Nested relations (included in list/getById)
  bookingType: bookingTypeSummarySchema.optional(),
  bookingReason: bookingReasonSummarySchema.optional(),
  employee: employeeSummarySchema.optional(),
})

type BookingOutput = z.infer<typeof bookingOutputSchema>

// --- Input Schemas ---

const listInputSchema = z
  .object({
    page: z.number().int().positive().optional().default(1),
    pageSize: z.number().int().min(1).max(100).optional().default(50),
    employeeId: z.string().optional(),
    fromDate: z.string().date().optional(), // YYYY-MM-DD
    toDate: z.string().date().optional(), // YYYY-MM-DD
    bookingTypeId: z.string().optional(),
    source: z.string().optional(),
  })
  .optional()

const createInputSchema = z.object({
  employeeId: z.string(),
  bookingTypeId: z.string(),
  bookingDate: z.string().date(), // YYYY-MM-DD
  time: z.string().regex(/^\d{2}:\d{2}$/, "Time must be HH:MM format"),
  notes: z.string().optional(),
  bookingReasonId: z.string().optional(),
})

const updateInputSchema = z.object({
  id: z.string(),
  time: z
    .string()
    .regex(/^\d{2}:\d{2}$/, "Time must be HH:MM format")
    .optional(),
  notes: z.string().nullable().optional(),
})

// --- Mapping Functions ---

/**
 * Maps a Prisma Booking record (with relations) to the output schema shape.
 * Mirrors Go modelToResponse.
 */
function mapToOutput(record: Record<string, unknown>): BookingOutput {
  const bookingType = record.bookingType as {
    id: string
    code: string
    name: string
    direction: string
  } | null | undefined
  const bookingReason = record.bookingReason as {
    id: string
    code: string
    label: string
  } | null | undefined
  const employee = record.employee as {
    id: string
    personnelNumber: string
    firstName: string
    lastName: string
    departmentId: string | null
  } | null | undefined

  const result: BookingOutput = {
    id: record.id as string,
    tenantId: record.tenantId as string,
    employeeId: record.employeeId as string,
    bookingDate: record.bookingDate as Date,
    bookingTypeId: record.bookingTypeId as string,
    originalTime: record.originalTime as number,
    editedTime: record.editedTime as number,
    calculatedTime: (record.calculatedTime as number | null) ?? null,
    pairId: (record.pairId as string | null) ?? null,
    source: (record.source as string | null) ?? null,
    terminalId: (record.terminalId as string | null) ?? null,
    notes: (record.notes as string | null) ?? null,
    bookingReasonId: (record.bookingReasonId as string | null) ?? null,
    isAutoGenerated: record.isAutoGenerated as boolean,
    originalBookingId: (record.originalBookingId as string | null) ?? null,
    createdAt: record.createdAt as Date,
    updatedAt: record.updatedAt as Date,
    createdBy: (record.createdBy as string | null) ?? null,
    updatedBy: (record.updatedBy as string | null) ?? null,
  }

  if (bookingType !== undefined) {
    result.bookingType = bookingType
      ? {
          id: bookingType.id,
          code: bookingType.code,
          name: bookingType.name,
          direction: bookingType.direction,
        }
      : null
  }

  if (bookingReason !== undefined) {
    result.bookingReason = bookingReason
      ? {
          id: bookingReason.id,
          code: bookingReason.code,
          label: bookingReason.label,
        }
      : null
  }

  if (employee !== undefined) {
    result.employee = employee
      ? {
          id: employee.id,
          personnelNumber: employee.personnelNumber,
          firstName: employee.firstName,
          lastName: employee.lastName,
          departmentId: employee.departmentId,
        }
      : null
  }

  return result
}

// --- Router ---

export const bookingsRouter = createTRPCRouter({
  /**
   * bookings.list -- Returns paginated bookings for the current tenant.
   *
   * Supports filters: employeeId, fromDate, toDate, bookingTypeId, source.
   * Applies data scope filtering via employee relation.
   * Orders by bookingDate DESC, editedTime DESC.
   *
   * Requires: time_tracking.view_all permission
   */
  list: tenantProcedure
    .use(requirePermission(VIEW_ALL))
    .use(applyDataScope())
    .input(listInputSchema)
    .output(
      z.object({
        items: z.array(bookingOutputSchema),
        total: z.number(),
      })
    )
    .query(async ({ ctx, input }) => {
      try {
        const tenantId = ctx.tenantId!
        const dataScope = (ctx as unknown as { dataScope: DataScope }).dataScope

        const { items, total } = await bookingsService.list(
          ctx.prisma,
          tenantId,
          {
            page: input?.page ?? 1,
            pageSize: input?.pageSize ?? 50,
            employeeId: input?.employeeId,
            fromDate: input?.fromDate,
            toDate: input?.toDate,
            bookingTypeId: input?.bookingTypeId,
            source: input?.source,
            dataScope,
          }
        )

        return {
          items: items.map((item) =>
            mapToOutput(item as unknown as Record<string, unknown>)
          ),
          total,
        }
      } catch (err) {
        handleServiceError(err)
      }
    }),

  /**
   * bookings.getById -- Returns a single booking by ID.
   *
   * Tenant-scoped. Data scope enforced after fetch.
   * Includes bookingType, bookingReason, and employee relations.
   *
   * Requires: time_tracking.view_own OR time_tracking.view_all permission
   */
  getById: tenantProcedure
    .use(requirePermission(VIEW_OWN, VIEW_ALL))
    .use(applyDataScope())
    .input(z.object({ id: z.string() }))
    .output(bookingOutputSchema)
    .query(async ({ ctx, input }) => {
      try {
        const tenantId = ctx.tenantId!
        const dataScope = (ctx as unknown as { dataScope: DataScope }).dataScope

        const booking = await bookingsService.getById(
          ctx.prisma,
          tenantId,
          input.id,
          dataScope
        )

        return mapToOutput(booking as unknown as Record<string, unknown>)
      } catch (err) {
        handleServiceError(err)
      }
    }),

  /**
   * bookings.create -- Creates a new booking.
   *
   * Validates employee, booking type, and optional booking reason.
   * Time is provided as HH:MM string and converted to minutes from midnight.
   * Source is always set to "web".
   * Creates derived booking if booking reason has adjustment config.
   * Triggers day recalculation after booking creation.
   *
   * Requires: time_tracking.edit permission
   */
  create: tenantProcedure
    .use(requirePermission(EDIT))
    .use(applyDataScope())
    .input(createInputSchema)
    .output(bookingOutputSchema)
    .mutation(async ({ ctx, input }) => {
      try {
        const tenantId = ctx.tenantId!
        const dataScope = (ctx as unknown as { dataScope: DataScope }).dataScope

        const booking = await bookingsService.createBooking(
          ctx.prisma,
          tenantId,
          input,
          dataScope,
          ctx.user!.id
        )

        return mapToOutput(booking as unknown as Record<string, unknown>)
      } catch (err) {
        handleServiceError(err)
      }
    }),

  /**
   * bookings.update -- Updates an existing booking.
   *
   * Only editedTime and notes can be updated.
   * When editedTime changes, calculatedTime is cleared (set to null).
   * Triggers day recalculation after booking update.
   *
   * Requires: time_tracking.edit permission
   */
  update: tenantProcedure
    .use(requirePermission(EDIT))
    .use(applyDataScope())
    .input(updateInputSchema)
    .output(bookingOutputSchema)
    .mutation(async ({ ctx, input }) => {
      try {
        const tenantId = ctx.tenantId!
        const dataScope = (ctx as unknown as { dataScope: DataScope }).dataScope

        const updated = await bookingsService.updateBooking(
          ctx.prisma,
          tenantId,
          input,
          dataScope,
          ctx.user!.id
        )

        return mapToOutput(updated as unknown as Record<string, unknown>)
      } catch (err) {
        handleServiceError(err)
      }
    }),

  /**
   * bookings.delete -- Deletes a booking.
   *
   * Hard delete. Deletes derived bookings first (in a transaction).
   * Triggers day recalculation after booking deletion.
   *
   * Requires: time_tracking.edit + booking_overview.delete_bookings permission
   */
  delete: tenantProcedure
    .use(requirePermission(EDIT))
    .use(requirePermission(DELETE_BOOKINGS))
    .use(applyDataScope())
    .input(z.object({ id: z.string() }))
    .output(z.object({ success: z.boolean() }))
    .mutation(async ({ ctx, input }) => {
      try {
        const tenantId = ctx.tenantId!
        const dataScope = (ctx as unknown as { dataScope: DataScope }).dataScope

        await bookingsService.deleteBooking(
          ctx.prisma,
          tenantId,
          input.id,
          dataScope
        )

        return { success: true }
      } catch (err) {
        handleServiceError(err)
      }
    }),

  /**
   * bookings.getLogs -- Returns audit log entries for a specific booking.
   *
   * Queries AuditLog where entityType='booking' and entityId=bookingId.
   *
   * Replaces: GET /bookings/{id}/logs
   *
   * Requires: time_tracking.view_own or time_tracking.view_all
   */
  getLogs: tenantProcedure
    .use(requirePermission(VIEW_OWN, VIEW_ALL))
    .input(z.object({ id: z.string() }))
    .output(
      z.object({
        items: z.array(
          z.object({
            id: z.string(),
            userId: z.string().nullable(),
            action: z.string(),
            entityType: z.string(),
            entityId: z.string(),
            entityName: z.string().nullable(),
            changes: z.any().nullable(),
            metadata: z.any().nullable(),
            performedAt: z.date(),
          })
        ),
      })
    )
    .query(async ({ ctx, input }) => {
      try {
        const logs = await ctx.prisma.auditLog.findMany({
          where: {
            tenantId: ctx.tenantId!,
            entityType: "booking",
            entityId: input.id,
          },
          orderBy: { performedAt: "desc" },
        })
        return { items: logs }
      } catch (err) {
        handleServiceError(err)
      }
    }),
})
