/**
 * Tests for DailyCalcService Pure Helper Functions
 *
 * All pure functions tested without any database dependencies.
 */

import { describe, it, expect } from "vitest"
import {
  sameDate,
  addDays,
  dateOnly,
  isBreakBooking,
  isBreakBookingType,
  bookingDirection,
  effectiveTime,
  sortedBookings,
  filterBookingsByDate,
  partitionBookingsByDate,
  pairWorkBookingsAcrossDays,
  applyDayChangeBehavior,
  findFirstLastWorkBookings,
  getHolidayCredit,
  hasShiftDetection,
  getAlternativePlanIDs,
  getEffectiveRegularHours,
  convertBonusesToSurchargeConfigs,
  calculateAbsenceCredit,
  getCreditMultiplier,
} from "../daily-calc.helpers"
import type { BookingWithType, DayPlanWithDetails } from "../daily-calc.types"

// --- Test Helpers ---

// We use `as unknown as T` pattern extensively in tests because
// we only need the fields that the tested function actually reads.

const defaultBookingType = {
  id: "bt1",
  tenantId: "t1",
  code: "COME",
  name: "Come",
  description: null,
  direction: "in" as const,
  category: "work",
  accountId: null,
  requiresReason: false,
  isSystem: false,
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date(),
}

/** Create a minimal BookingWithType for testing */
function makeBooking(overrides: Record<string, unknown> = {}): BookingWithType {
  const { bookingType: btOverride, ...rest } = overrides
  const bt = btOverride === null
    ? null
    : { ...defaultBookingType, ...(btOverride as Record<string, unknown> ?? {}) }

  return {
    id: "b1",
    tenantId: "t1",
    employeeId: "e1",
    bookingDate: new Date("2026-03-01T00:00:00Z"),
    bookingTypeId: "bt1",
    originalTime: 480,
    editedTime: 480,
    calculatedTime: null,
    pairId: null,
    source: "web",
    terminalId: null,
    notes: null,
    bookingReasonId: null,
    isAutoGenerated: false,
    originalBookingId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: null,
    updatedBy: null,
    ...rest,
    bookingType: bt,
  } as unknown as BookingWithType
}

function makeDayPlan(overrides: Record<string, unknown> = {}): DayPlanWithDetails {
  return {
    id: "dp1",
    tenantId: "t1",
    code: "STD",
    name: "Standard",
    description: null,
    planType: "fixed",
    comeFrom: 420,
    comeTo: 540,
    goFrom: 960,
    goTo: 1080,
    coreStart: null,
    coreEnd: null,
    regularHours: 480,
    regularHours2: null,
    fromEmployeeMaster: false,
    toleranceComePlus: 15,
    toleranceComeMinus: 15,
    toleranceGoPlus: 15,
    toleranceGoMinus: 15,
    roundingComeType: null,
    roundingComeInterval: null,
    roundingGoType: null,
    roundingGoInterval: null,
    minWorkTime: null,
    maxNetWorkTime: null,
    variableWorkTime: false,
    roundAllBookings: false,
    roundingComeAddValue: null,
    roundingGoAddValue: null,
    holidayCreditCat1: 480,
    holidayCreditCat2: 240,
    holidayCreditCat3: null,
    vacationDeduction: "1.00",
    noBookingBehavior: "error",
    dayChangeBehavior: "none",
    shiftDetectArriveFrom: null,
    shiftDetectArriveTo: null,
    shiftDetectDepartFrom: null,
    shiftDetectDepartTo: null,
    shiftAltPlan1: null,
    shiftAltPlan2: null,
    shiftAltPlan3: null,
    shiftAltPlan4: null,
    shiftAltPlan5: null,
    shiftAltPlan6: null,
    netAccountId: null,
    capAccountId: null,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    breaks: [],
    bonuses: [],
    ...overrides,
  } as unknown as DayPlanWithDetails
}

// --- Tests ---

describe("daily-calc helpers", () => {
  describe("sameDate", () => {
    it("returns true for same UTC date", () => {
      const a = new Date("2026-03-01T00:00:00Z")
      const b = new Date("2026-03-01T23:59:59Z")
      expect(sameDate(a, b)).toBe(true)
    })

    it("returns false for different UTC dates", () => {
      const a = new Date("2026-03-01T00:00:00Z")
      const b = new Date("2026-03-02T00:00:00Z")
      expect(sameDate(a, b)).toBe(false)
    })

    it("returns true for identical dates", () => {
      const d = new Date("2026-06-15T12:00:00Z")
      expect(sameDate(d, d)).toBe(true)
    })
  })

  describe("addDays", () => {
    it("adds days correctly", () => {
      const date = new Date("2026-03-01T00:00:00Z")
      const result = addDays(date, 3)
      expect(result.toISOString()).toBe("2026-03-04T00:00:00.000Z")
    })

    it("subtracts days correctly", () => {
      const date = new Date("2026-03-05T00:00:00Z")
      const result = addDays(date, -2)
      expect(result.toISOString()).toBe("2026-03-03T00:00:00.000Z")
    })

    it("handles month boundary", () => {
      const date = new Date("2026-01-31T00:00:00Z")
      const result = addDays(date, 1)
      expect(result.toISOString()).toBe("2026-02-01T00:00:00.000Z")
    })

    it("returns midnight UTC", () => {
      const date = new Date("2026-03-01T15:30:00Z")
      const result = addDays(date, 1)
      expect(result.getUTCHours()).toBe(0)
      expect(result.getUTCMinutes()).toBe(0)
    })
  })

  describe("dateOnly", () => {
    it("strips time component", () => {
      const date = new Date("2026-03-01T15:30:45.123Z")
      const result = dateOnly(date)
      expect(result.toISOString()).toBe("2026-03-01T00:00:00.000Z")
    })
  })

  describe("isBreakBooking", () => {
    it("returns true for P1 code", () => {
      const b = makeBooking({ bookingType: { code: "P1" } })
      expect(isBreakBooking(b)).toBe(true)
    })

    it("returns true for BREAK_START code", () => {
      const b = makeBooking({ bookingType: { code: "BREAK_START" } })
      expect(isBreakBooking(b)).toBe(true)
    })

    it("returns true for BREAK_END code (case insensitive)", () => {
      const b = makeBooking({ bookingType: { code: "break_end" } })
      expect(isBreakBooking(b)).toBe(true)
    })

    it("returns false for COME code", () => {
      const b = makeBooking({ bookingType: { code: "COME" } })
      expect(isBreakBooking(b)).toBe(false)
    })

    it("returns false when bookingType is missing", () => {
      const b = makeBooking({ bookingType: null })
      expect(isBreakBooking(b)).toBe(false)
    })
  })

  describe("isBreakBookingType", () => {
    it("recognizes P1", () => expect(isBreakBookingType("P1")).toBe(true))
    it("recognizes P2", () => expect(isBreakBookingType("P2")).toBe(true))
    it("recognizes BREAK_START", () => expect(isBreakBookingType("BREAK_START")).toBe(true))
    it("recognizes BREAK_END", () => expect(isBreakBookingType("BREAK_END")).toBe(true))
    it("is case insensitive", () => expect(isBreakBookingType("p1")).toBe(true))
    it("rejects COME", () => expect(isBreakBookingType("COME")).toBe(false))
    it("rejects GO", () => expect(isBreakBookingType("GO")).toBe(false))
  })

  describe("bookingDirection", () => {
    it("returns 'in' for in direction", () => {
      const b = makeBooking({ bookingType: { direction: "in" } })
      expect(bookingDirection(b)).toBe("in")
    })

    it("returns 'out' for out direction", () => {
      const b = makeBooking({ bookingType: { direction: "out" } })
      expect(bookingDirection(b)).toBe("out")
    })

    it("defaults to 'in' when no bookingType", () => {
      const b = makeBooking({ bookingType: null })
      expect(bookingDirection(b)).toBe("in")
    })
  })

  describe("effectiveTime", () => {
    it("returns calculatedTime when set", () => {
      const b = makeBooking({ editedTime: 480, calculatedTime: 485 })
      expect(effectiveTime(b)).toBe(485)
    })

    it("returns editedTime when calculatedTime is null", () => {
      const b = makeBooking({ editedTime: 480, calculatedTime: null })
      expect(effectiveTime(b)).toBe(480)
    })

    it("returns calculatedTime when it is 0", () => {
      const b = makeBooking({ editedTime: 480, calculatedTime: 0 })
      expect(effectiveTime(b)).toBe(0)
    })
  })

  describe("sortedBookings", () => {
    it("sorts by date, then time, then id", () => {
      const b1 = makeBooking({ id: "a", bookingDate: new Date("2026-03-01T00:00:00Z"), editedTime: 480 })
      const b2 = makeBooking({ id: "b", bookingDate: new Date("2026-03-01T00:00:00Z"), editedTime: 480 })
      const b3 = makeBooking({ id: "c", bookingDate: new Date("2026-03-01T00:00:00Z"), editedTime: 960 })
      const b4 = makeBooking({ id: "d", bookingDate: new Date("2026-03-02T00:00:00Z"), editedTime: 480 })

      const sorted = sortedBookings([b4, b3, b2, b1])
      expect(sorted.map((b) => b.id)).toEqual(["a", "b", "c", "d"])
    })
  })

  describe("filterBookingsByDate", () => {
    it("only includes matching date", () => {
      const date = new Date("2026-03-01T00:00:00Z")
      const b1 = makeBooking({ id: "a", bookingDate: new Date("2026-02-28T00:00:00Z") })
      const b2 = makeBooking({ id: "b", bookingDate: date })
      const b3 = makeBooking({ id: "c", bookingDate: new Date("2026-03-02T00:00:00Z") })

      const result = filterBookingsByDate([b1, b2, b3], date)
      expect(result.map((b) => b.id)).toEqual(["b"])
    })

    it("deduplicates by id", () => {
      const date = new Date("2026-03-01T00:00:00Z")
      const b1 = makeBooking({ id: "a", bookingDate: date })
      const b2 = makeBooking({ id: "a", bookingDate: date }) // duplicate

      const result = filterBookingsByDate([b1, b2], date)
      expect(result.length).toBe(1)
    })
  })

  describe("partitionBookingsByDate", () => {
    it("partitions into prev/current/next", () => {
      const date = new Date("2026-03-02T00:00:00Z")
      const bPrev = makeBooking({ id: "p", bookingDate: new Date("2026-03-01T00:00:00Z") })
      const bCurr = makeBooking({ id: "c", bookingDate: date })
      const bNext = makeBooking({ id: "n", bookingDate: new Date("2026-03-03T00:00:00Z") })
      const bOther = makeBooking({ id: "o", bookingDate: new Date("2026-03-05T00:00:00Z") })

      const { prev, current, next } = partitionBookingsByDate(
        [bPrev, bCurr, bNext, bOther],
        date
      )
      expect(prev.map((b) => b.id)).toEqual(["p"])
      expect(current.map((b) => b.id)).toEqual(["c"])
      expect(next.map((b) => b.id)).toEqual(["n"])
    })
  })

  describe("pairWorkBookingsAcrossDays", () => {
    it("pairs same-day IN/OUT", () => {
      const bIn = makeBooking({
        id: "in1",
        editedTime: 480,
        bookingType: { code: "COME", direction: "in" },
      })
      const bOut = makeBooking({
        id: "out1",
        editedTime: 1020,
        bookingType: { code: "GO", direction: "out" },
      })

      const pairs = pairWorkBookingsAcrossDays([], [bIn, bOut], [])
      expect(pairs.length).toBe(1)
      expect(pairs[0]!.arrival.booking.id).toBe("in1")
      expect(pairs[0]!.departure.booking.id).toBe("out1")
    })

    it("pairs cross-midnight IN(day0)/OUT(day1)", () => {
      const bIn = makeBooking({
        id: "in1",
        editedTime: 1380,
        bookingType: { code: "COME", direction: "in" },
      })
      const bOut = makeBooking({
        id: "out1",
        editedTime: 360,
        bookingType: { code: "GO", direction: "out" },
      })

      const pairs = pairWorkBookingsAcrossDays([], [bIn], [bOut])
      expect(pairs.length).toBe(1)
      expect(pairs[0]!.arrival.offset).toBe(0)
      expect(pairs[0]!.departure.offset).toBe(1)
    })

    it("handles unpaired arrivals", () => {
      const bIn = makeBooking({
        id: "in1",
        editedTime: 480,
        bookingType: { code: "COME", direction: "in" },
      })

      const pairs = pairWorkBookingsAcrossDays([], [bIn], [])
      expect(pairs.length).toBe(0)
    })

    it("pairs FIFO with multiple pairs", () => {
      const bIn1 = makeBooking({ id: "in1", editedTime: 480, bookingType: { code: "COME", direction: "in" } })
      const bOut1 = makeBooking({ id: "out1", editedTime: 720, bookingType: { code: "GO", direction: "out" } })
      const bIn2 = makeBooking({ id: "in2", editedTime: 780, bookingType: { code: "COME", direction: "in" } })
      const bOut2 = makeBooking({ id: "out2", editedTime: 1020, bookingType: { code: "GO", direction: "out" } })

      const pairs = pairWorkBookingsAcrossDays([], [bIn1, bOut1, bIn2, bOut2], [])
      expect(pairs.length).toBe(2)
      expect(pairs[0]!.arrival.booking.id).toBe("in1")
      expect(pairs[0]!.departure.booking.id).toBe("out1")
      expect(pairs[1]!.arrival.booking.id).toBe("in2")
      expect(pairs[1]!.departure.booking.id).toBe("out2")
    })

    it("ignores break bookings", () => {
      const bIn = makeBooking({ id: "in1", editedTime: 480, bookingType: { code: "COME", direction: "in" } })
      const bBreak = makeBooking({ id: "br1", editedTime: 720, bookingType: { code: "P1", direction: "out" } })
      const bOut = makeBooking({ id: "out1", editedTime: 1020, bookingType: { code: "GO", direction: "out" } })

      const pairs = pairWorkBookingsAcrossDays([], [bIn, bBreak, bOut], [])
      expect(pairs.length).toBe(1)
      expect(pairs[0]!.departure.booking.id).toBe("out1")
    })
  })

  describe("applyDayChangeBehavior", () => {
    const date = new Date("2026-03-02T00:00:00Z")
    const prevDate = new Date("2026-03-01T00:00:00Z")
    const nextDate = new Date("2026-03-03T00:00:00Z")

    describe("at_arrival", () => {
      it("includes next-day departure for arrival on current day", () => {
        const bIn = makeBooking({
          id: "in1",
          bookingDate: date,
          editedTime: 1380,
          bookingType: { code: "COME", direction: "in" },
        })
        const bOut = makeBooking({
          id: "out1",
          bookingDate: nextDate,
          editedTime: 360,
          bookingType: { code: "GO", direction: "out" },
        })

        const result = applyDayChangeBehavior(date, "at_arrival", [bIn, bOut])
        const ids = result.map((b) => b.id)
        expect(ids).toContain("in1")
        expect(ids).toContain("out1")
      })

      it("excludes current-day departure for arrival on previous day", () => {
        const bIn = makeBooking({
          id: "in1",
          bookingDate: prevDate,
          editedTime: 1380,
          bookingType: { code: "COME", direction: "in" },
        })
        const bOut = makeBooking({
          id: "out1",
          bookingDate: date,
          editedTime: 360,
          bookingType: { code: "GO", direction: "out" },
        })

        const result = applyDayChangeBehavior(date, "at_arrival", [bIn, bOut])
        const ids = result.map((b) => b.id)
        expect(ids).not.toContain("out1")
      })
    })

    describe("at_departure", () => {
      it("includes previous-day arrival for departure on current day", () => {
        const bIn = makeBooking({
          id: "in1",
          bookingDate: prevDate,
          editedTime: 1380,
          bookingType: { code: "COME", direction: "in" },
        })
        const bOut = makeBooking({
          id: "out1",
          bookingDate: date,
          editedTime: 360,
          bookingType: { code: "GO", direction: "out" },
        })

        const result = applyDayChangeBehavior(date, "at_departure", [bIn, bOut])
        const ids = result.map((b) => b.id)
        expect(ids).toContain("in1")
        expect(ids).toContain("out1")
      })

      it("excludes current-day arrival for departure on next day", () => {
        const bIn = makeBooking({
          id: "in1",
          bookingDate: date,
          editedTime: 1380,
          bookingType: { code: "COME", direction: "in" },
        })
        const bOut = makeBooking({
          id: "out1",
          bookingDate: nextDate,
          editedTime: 360,
          bookingType: { code: "GO", direction: "out" },
        })

        const result = applyDayChangeBehavior(date, "at_departure", [bIn, bOut])
        const ids = result.map((b) => b.id)
        expect(ids).not.toContain("in1")
      })
    })
  })

  describe("findFirstLastWorkBookings", () => {
    it("finds earliest IN and latest OUT", () => {
      const bookings = [
        makeBooking({ id: "in1", editedTime: 480, bookingType: { code: "COME", direction: "in" } }),
        makeBooking({ id: "out1", editedTime: 720, bookingType: { code: "GO", direction: "out" } }),
        makeBooking({ id: "in2", editedTime: 420, bookingType: { code: "COME", direction: "in" } }),
        makeBooking({ id: "out2", editedTime: 1020, bookingType: { code: "GO", direction: "out" } }),
      ]

      const { firstCome, lastGo } = findFirstLastWorkBookings(bookings)
      expect(firstCome).toBe(420)
      expect(lastGo).toBe(1020)
    })

    it("returns null for empty bookings", () => {
      const { firstCome, lastGo } = findFirstLastWorkBookings([])
      expect(firstCome).toBeNull()
      expect(lastGo).toBeNull()
    })

    it("ignores break bookings", () => {
      const bookings = [
        makeBooking({ id: "in1", editedTime: 480, bookingType: { code: "COME", direction: "in" } }),
        makeBooking({ id: "br1", editedTime: 300, bookingType: { code: "P1", direction: "in" } }),
        makeBooking({ id: "out1", editedTime: 1020, bookingType: { code: "GO", direction: "out" } }),
        makeBooking({ id: "br2", editedTime: 1200, bookingType: { code: "BREAK_END", direction: "out" } }),
      ]

      const { firstCome, lastGo } = findFirstLastWorkBookings(bookings)
      expect(firstCome).toBe(480)
      expect(lastGo).toBe(1020)
    })
  })

  describe("getHolidayCredit", () => {
    const dp = makeDayPlan({
      holidayCreditCat1: 480,
      holidayCreditCat2: 240,
      holidayCreditCat3: null,
    })

    it("returns cat1 for category 1", () => {
      expect(getHolidayCredit(dp, 1)).toBe(480)
    })

    it("returns cat2 for category 2", () => {
      expect(getHolidayCredit(dp, 2)).toBe(240)
    })

    it("returns 0 for unconfigured category", () => {
      expect(getHolidayCredit(dp, 3)).toBe(0)
    })

    it("returns 0 for unknown category", () => {
      expect(getHolidayCredit(dp, 99)).toBe(0)
    })
  })

  describe("hasShiftDetection", () => {
    it("returns false when no shift fields set", () => {
      expect(hasShiftDetection(makeDayPlan())).toBe(false)
    })

    it("returns true when arriveFrom is set", () => {
      expect(hasShiftDetection(makeDayPlan({ shiftDetectArriveFrom: 400 }))).toBe(true)
    })

    it("returns true when departTo is set", () => {
      expect(hasShiftDetection(makeDayPlan({ shiftDetectDepartTo: 1000 }))).toBe(true)
    })
  })

  describe("getAlternativePlanIDs", () => {
    it("returns empty for no alternatives", () => {
      expect(getAlternativePlanIDs(makeDayPlan())).toEqual([])
    })

    it("collects non-null alternatives", () => {
      const dp = makeDayPlan({
        shiftAltPlan1: "alt1",
        shiftAltPlan2: null,
        shiftAltPlan3: "alt3",
      })
      expect(getAlternativePlanIDs(dp)).toEqual(["alt1", "alt3"])
    })
  })

  describe("getEffectiveRegularHours", () => {
    it("uses employee master when configured", () => {
      const dp = makeDayPlan({ fromEmployeeMaster: true, regularHours: 480 })
      expect(getEffectiveRegularHours(dp, false, 420)).toBe(420)
    })

    it("uses regularHours2 for absence day", () => {
      const dp = makeDayPlan({ regularHours: 480, regularHours2: 240 })
      expect(getEffectiveRegularHours(dp, true, null)).toBe(240)
    })

    it("defaults to regularHours", () => {
      const dp = makeDayPlan({ regularHours: 480 })
      expect(getEffectiveRegularHours(dp, false, null)).toBe(480)
    })

    it("prefers employee master over regularHours2", () => {
      const dp = makeDayPlan({
        fromEmployeeMaster: true,
        regularHours: 480,
        regularHours2: 240,
      })
      expect(getEffectiveRegularHours(dp, true, 420)).toBe(420)
    })

    it("falls back to regularHours2 when employee master is enabled but null", () => {
      const dp = makeDayPlan({
        fromEmployeeMaster: true,
        regularHours: 480,
        regularHours2: 240,
      })
      expect(getEffectiveRegularHours(dp, true, null)).toBe(240)
    })
  })

  describe("convertBonusesToSurchargeConfigs", () => {
    it("maps bonus fields to surcharge config", () => {
      const bonuses = [
        {
          id: "b1",
          dayPlanId: "dp1",
          accountId: "a1",
          timeFrom: 1320,
          timeTo: 360,
          calculationType: "per_minute",
          valueMinutes: 0,
          minWorkMinutes: null,
          appliesOnHoliday: false,
          sortOrder: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
          account: { id: "a1", code: "NIGHT", name: "Night Bonus" } as DayPlanWithDetails["bonuses"][0]["account"],
        },
      ] as DayPlanWithDetails["bonuses"]

      const configs = convertBonusesToSurchargeConfigs(bonuses)
      expect(configs.length).toBe(1)
      expect(configs[0]!.accountId).toBe("a1")
      expect(configs[0]!.accountCode).toBe("NIGHT")
      expect(configs[0]!.timeFrom).toBe(1320)
      expect(configs[0]!.timeTo).toBe(360)
      expect(configs[0]!.appliesOnHoliday).toBe(false)
      expect(configs[0]!.appliesOnWorkday).toBe(true)
    })

    it("sets appliesOnWorkday as inverse of appliesOnHoliday", () => {
      const bonuses = [
        {
          id: "b1",
          dayPlanId: "dp1",
          accountId: "a1",
          timeFrom: 0,
          timeTo: 1440,
          calculationType: "per_minute",
          valueMinutes: 0,
          minWorkMinutes: null,
          appliesOnHoliday: true,
          sortOrder: 0,
          createdAt: new Date(),
          updatedAt: new Date(),
          account: { id: "a1", code: "HOL", name: "Holiday" } as DayPlanWithDetails["bonuses"][0]["account"],
        },
      ] as DayPlanWithDetails["bonuses"]

      const configs = convertBonusesToSurchargeConfigs(bonuses)
      expect(configs[0]!.appliesOnHoliday).toBe(true)
      expect(configs[0]!.appliesOnWorkday).toBe(false)
    })
  })

  describe("getCreditMultiplier", () => {
    it("returns 0 for portion 0", () => expect(getCreditMultiplier(0)).toBe(0))
    it("returns 1 for portion 1", () => expect(getCreditMultiplier(1)).toBe(1))
    it("returns 0.5 for portion 2", () => expect(getCreditMultiplier(2)).toBe(0.5))
    it("returns 1 for unknown portion", () => expect(getCreditMultiplier(99)).toBe(1))
  })

  describe("calculateAbsenceCredit", () => {
    it("full portion = regelarbeitszeit * duration", () => {
      expect(calculateAbsenceCredit(480, 1, 1.0)).toBe(480)
    })

    it("half portion = 0.5 * regelarbeitszeit * duration", () => {
      expect(calculateAbsenceCredit(480, 2, 1.0)).toBe(240)
    })

    it("none portion = 0", () => {
      expect(calculateAbsenceCredit(480, 0, 1.0)).toBe(0)
    })

    it("handles fractional duration", () => {
      expect(calculateAbsenceCredit(480, 1, 0.5)).toBe(240)
    })

    it("floors the result", () => {
      expect(calculateAbsenceCredit(481, 2, 1.0)).toBe(240)
    })
  })
})
