/**
 * AUDIT-003 Verification Tests
 *
 * Verify that the fix for missing tenantId propagation in DailyCalcService
 * is correctly applied. Every Prisma query must include tenantId in its
 * where clause to maintain tenant isolation.
 *
 * These tests mock Prisma and inspect the where clause arguments passed
 * to each query method.
 */

import { describe, it, expect, vi, beforeEach } from "vitest"
import { DailyCalcService } from "../daily-calc"
import { loadEmployeeCalcContext, loadTenantCalcCache } from "../daily-calc.context"
import type { PrismaClient } from "@/generated/prisma/client"

// --- Constants ---

const TENANT_ID = "tenant-audit-003"
const EMPLOYEE_ID = "emp-audit-003"
const DATE = new Date("2026-03-15T00:00:00Z")

// --- Mock Prisma Client ---

function createPrismaMocks() {
  return {
    holiday: {
      findFirst: vi.fn().mockResolvedValue(null),
      findMany: vi.fn().mockResolvedValue([]),
    },
    employeeDayPlan: {
      findFirst: vi.fn().mockResolvedValue(null),
      findMany: vi.fn().mockResolvedValue([]),
    },
    booking: {
      findMany: vi.fn().mockResolvedValue([]),
      create: vi.fn(),
      update: vi.fn(),
      updateMany: vi.fn().mockResolvedValue({ count: 1 }),
    },
    employee: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    dailyValue: {
      findUnique: vi.fn().mockResolvedValue(null),
      findMany: vi.fn().mockResolvedValue([]),
      upsert: vi.fn().mockImplementation(async (args: { create: Record<string, unknown> }) => ({
        id: "dv-1",
        ...args.create,
      })),
    },
    dailyAccountValue: {
      deleteMany: vi.fn().mockResolvedValue({ count: 0 }),
      upsert: vi.fn().mockResolvedValue({}),
    },
    systemSetting: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    notification: {
      create: vi.fn().mockResolvedValue({}),
    },
    dayPlan: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    orderBooking: {
      deleteMany: vi.fn().mockResolvedValue({ count: 0 }),
      create: vi.fn().mockResolvedValue({}),
    },
    $queryRaw: vi.fn().mockResolvedValue([]),
    $executeRaw: vi.fn().mockResolvedValue(0),
    $transaction: vi.fn().mockImplementation(async (ops: Promise<unknown>[]) => {
      return Promise.all(ops)
    }),
  }
}

function createMockPrisma() {
  const mocks = createPrismaMocks()
  return { prisma: mocks as unknown as PrismaClient, mocks }
}

// --- Test Data Factories ---

function makeEmpDayPlan(overrides: Record<string, unknown> = {}) {
  return {
    id: "edp-1",
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    planDate: DATE,
    dayPlanId: "dp-1",
    shiftId: null,
    source: "tariff",
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    dayPlan: {
      id: "dp-1",
      tenantId: TENANT_ID,
      code: "STD",
      name: "Standard",
      description: null,
      planType: "fixed",
      comeFrom: 420,
      comeTo: 540,
      goFrom: 960,
      goTo: 1080,
      coreStart: null,
      coreEnd: null,
      regularHours: 480,
      regularHours2: null,
      fromEmployeeMaster: false,
      toleranceComePlus: 15,
      toleranceComeMinus: 15,
      toleranceGoPlus: 15,
      toleranceGoMinus: 15,
      roundingComeType: null,
      roundingComeInterval: null,
      roundingGoType: null,
      roundingGoInterval: null,
      minWorkTime: null,
      maxNetWorkTime: null,
      variableWorkTime: false,
      roundAllBookings: false,
      roundingComeAddValue: null,
      roundingGoAddValue: null,
      holidayCreditCat1: 480,
      holidayCreditCat2: 240,
      holidayCreditCat3: null,
      vacationDeduction: "1.00",
      noBookingBehavior: "error",
      dayChangeBehavior: "none",
      shiftDetectArriveFrom: null,
      shiftDetectArriveTo: null,
      shiftDetectDepartFrom: null,
      shiftDetectDepartTo: null,
      shiftAltPlan1: null,
      shiftAltPlan2: null,
      shiftAltPlan3: null,
      shiftAltPlan4: null,
      shiftAltPlan5: null,
      shiftAltPlan6: null,
      netAccountId: null,
      capAccountId: null,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      breaks: [],
      bonuses: [],
      ...overrides,
    },
    ...overrides,
  }
}

function makeBookingData(overrides: Record<string, unknown> = {}) {
  return {
    id: "b-1",
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    bookingDate: DATE,
    bookingTypeId: "bt-come",
    originalTime: 480,
    editedTime: 480,
    calculatedTime: null,
    pairId: null,
    source: "web",
    terminalId: null,
    notes: null,
    bookingReasonId: null,
    isAutoGenerated: false,
    originalBookingId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: null,
    updatedBy: null,
    bookingType: {
      id: "bt-come",
      tenantId: TENANT_ID,
      code: "COME",
      name: "Come",
      description: null,
      direction: "in",
      category: "work",
      accountId: null,
      requiresReason: false,
      isSystem: true,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ...overrides,
  }
}

// --- Tests ---

describe("AUDIT-003: DailyCalcService tenantId propagation", () => {
  let service: DailyCalcService
  let mocks: ReturnType<typeof createPrismaMocks>

  beforeEach(() => {
    const result = createMockPrisma()
    service = new DailyCalcService(result.prisma)
    mocks = result.mocks
  })

  // ===========================================================================
  // Test 1: tenantId propagation to all queries
  // ===========================================================================

  describe("AUDIT-003: tenantId propagation to all queries", () => {
    it("AUDIT-003: loadEmployeeDayPlan passes tenantId to employeeDayPlan.findFirst", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.employeeDayPlan.findFirst).toHaveBeenCalled()
      const call = mocks.employeeDayPlan.findFirst.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
      expect(call.where).toHaveProperty("employeeId", EMPLOYEE_ID)
    })

    it("AUDIT-003: employee.findFirst includes tenantId when resolving target hours from employee master", async () => {
      // Set up a day plan with fromEmployeeMaster=true to trigger employee lookup
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ fromEmployeeMaster: true })
      )
      mocks.employee.findFirst.mockResolvedValue({
        dailyTargetHours: "8.00",
      })

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.employee.findFirst).toHaveBeenCalled()
      const call = mocks.employee.findFirst.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
      expect(call.where).toHaveProperty("id", EMPLOYEE_ID)
    })

    it("AUDIT-003: employee.findFirst includes tenantId in applyNBRTargetWithOrder", async () => {
      // Set up no-booking with target_with_order behavior to trigger employee lookup
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "target_with_order" })
      )
      mocks.employee.findFirst.mockResolvedValue({
        id: EMPLOYEE_ID,
        tenantId: TENANT_ID,
        defaultOrderId: "order-1",
        defaultActivityId: "act-1",
      })

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // Find the employee.findFirst call for the target_with_order path
      const calls = mocks.employee.findFirst.mock.calls
      const targetWithOrderCall = calls.find(
        (c: unknown[]) => {
          const args = c[0] as { select?: Record<string, unknown> }
          return args.select?.defaultOrderId !== undefined
        }
      )
      expect(targetWithOrderCall).toBeDefined()
      const where = (targetWithOrderCall![0] as { where: Record<string, unknown> }).where
      expect(where).toHaveProperty("tenantId", TENANT_ID)
      expect(where).toHaveProperty("id", EMPLOYEE_ID)
    })

    it("AUDIT-003: employee.findFirst includes tenantId in notifyDailyCalcError", async () => {
      // Trigger error notification: no bookings with error behavior, no previous error
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "error" })
      )
      mocks.dailyValue.findUnique.mockResolvedValue(null)
      mocks.employee.findFirst.mockResolvedValue({ id: EMPLOYEE_ID })
      mocks.$queryRaw
        .mockResolvedValueOnce([]) // absence_days query
        .mockResolvedValueOnce([]) // absence_days query (step 7.5)
        .mockResolvedValueOnce([{ user_id: "u-1" }]) // user_tenants

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // The notifyDailyCalcError method calls employee.findFirst
      const calls = mocks.employee.findFirst.mock.calls
      expect(calls.length).toBeGreaterThan(0)

      // Check all employee.findFirst calls have tenantId
      for (const call of calls) {
        const where = (call[0] as { where: Record<string, unknown> }).where
        expect(where).toHaveProperty("tenantId", TENANT_ID)
      }
    })

    it("AUDIT-003: holiday.findFirst includes tenantId", async () => {
      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.holiday.findFirst).toHaveBeenCalled()
      const call = mocks.holiday.findFirst.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
    })
  })

  // ===========================================================================
  // Test 2: Booking update uses updateMany with tenantId
  // ===========================================================================

  describe("AUDIT-003: booking.updateMany uses tenantId", () => {
    it("AUDIT-003: booking write uses updateMany (not update) with tenantId in where clause", async () => {
      // Set up a normal calculation with bookings that produces calculatedTimes
      mocks.employeeDayPlan.findFirst.mockResolvedValue(makeEmpDayPlan())

      const comeBooking = makeBookingData({
        id: "b-come",
        editedTime: 480,
        bookingType: {
          id: "bt-come",
          tenantId: TENANT_ID,
          code: "COME",
          name: "Come",
          description: null,
          direction: "in",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      const goBooking = makeBookingData({
        id: "b-go",
        editedTime: 960,
        bookingType: {
          id: "bt-go",
          tenantId: TENANT_ID,
          code: "GO",
          name: "Go",
          description: null,
          direction: "out",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      mocks.booking.findMany.mockResolvedValue([comeBooking, goBooking])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // If calculatedTimes are produced, $transaction should be called with updateMany operations
      if (mocks.$transaction.mock.calls.length > 0) {
        // The $transaction receives an array of updateMany promises
        // Verify updateMany was called (not update)
        if (mocks.booking.updateMany.mock.calls.length > 0) {
          for (const call of mocks.booking.updateMany.mock.calls) {
            const args = call[0] as { where: Record<string, unknown> }
            expect(args.where).toHaveProperty("tenantId", TENANT_ID)
            expect(args.where).toHaveProperty("id")
          }
          // Verify the old .update was NOT called for booking calculated times
          expect(mocks.booking.update).not.toHaveBeenCalled()
        }
      }
    })

    it("AUDIT-003: booking.updateMany includes both id and tenantId in where clause", async () => {
      // Specifically test the transaction path by setting up bookings that
      // will have rounding applied (tolerance rounding triggers calculatedTimes)
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({
          toleranceComePlus: 15,
          toleranceComeMinus: 15,
          toleranceGoPlus: 15,
          toleranceGoMinus: 15,
        })
      )

      // Booking at 485 (within tolerance of comeFrom=420..comeTo=540)
      // The calculated time may differ from editedTime due to rounding
      const comeBooking = makeBookingData({
        id: "b-come-round",
        editedTime: 485,
        bookingType: {
          id: "bt-come",
          tenantId: TENANT_ID,
          code: "COME",
          name: "Come",
          description: null,
          direction: "in",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      const goBooking = makeBookingData({
        id: "b-go-round",
        editedTime: 965,
        bookingType: {
          id: "bt-go",
          tenantId: TENANT_ID,
          code: "GO",
          name: "Go",
          description: null,
          direction: "out",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      mocks.booking.findMany.mockResolvedValue([comeBooking, goBooking])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // If any updateMany calls occurred, verify they have tenantId
      for (const call of mocks.booking.updateMany.mock.calls) {
        const args = call[0] as { where: { id: string; tenantId: string } }
        expect(args.where.tenantId).toBe(TENANT_ID)
        expect(args.where.id).toBeDefined()
      }
    })
  })

  // ===========================================================================
  // Test 3: Context loader passes tenantId
  // ===========================================================================

  describe("AUDIT-003: context loader passes tenantId to all queries", () => {
    it("AUDIT-003: loadEmployeeCalcContext passes tenantId to employeeDayPlan.findMany", async () => {
      const { prisma, mocks: ctxMocks } = createMockPrisma()
      const tenantCache = {
        holidays: new Map(),
        systemSettings: { roundingRelativeToPlan: false },
      }

      await loadEmployeeCalcContext(
        prisma,
        tenantCache,
        TENANT_ID,
        EMPLOYEE_ID,
        DATE,
        DATE
      )

      expect(ctxMocks.employeeDayPlan.findMany).toHaveBeenCalledTimes(1)
      const call = ctxMocks.employeeDayPlan.findMany.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
      expect(call.where).toHaveProperty("employeeId", EMPLOYEE_ID)
    })

    it("AUDIT-003: loadEmployeeCalcContext passes tenantId to dailyValue.findMany", async () => {
      const { prisma, mocks: ctxMocks } = createMockPrisma()
      const tenantCache = {
        holidays: new Map(),
        systemSettings: { roundingRelativeToPlan: false },
      }

      await loadEmployeeCalcContext(
        prisma,
        tenantCache,
        TENANT_ID,
        EMPLOYEE_ID,
        DATE,
        DATE
      )

      expect(ctxMocks.dailyValue.findMany).toHaveBeenCalledTimes(1)
      const call = ctxMocks.dailyValue.findMany.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
      expect(call.where).toHaveProperty("employeeId", EMPLOYEE_ID)
    })

    it("AUDIT-003: loadEmployeeCalcContext passes tenantId to employee.findFirst", async () => {
      const { prisma, mocks: ctxMocks } = createMockPrisma()
      const tenantCache = {
        holidays: new Map(),
        systemSettings: { roundingRelativeToPlan: false },
      }

      await loadEmployeeCalcContext(
        prisma,
        tenantCache,
        TENANT_ID,
        EMPLOYEE_ID,
        DATE,
        DATE
      )

      expect(ctxMocks.employee.findFirst).toHaveBeenCalledTimes(1)
      const call = ctxMocks.employee.findFirst.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
      expect(call.where).toHaveProperty("id", EMPLOYEE_ID)
    })

    it("AUDIT-003: loadEmployeeCalcContext passes tenantId to booking.findMany", async () => {
      const { prisma, mocks: ctxMocks } = createMockPrisma()
      const tenantCache = {
        holidays: new Map(),
        systemSettings: { roundingRelativeToPlan: false },
      }

      await loadEmployeeCalcContext(
        prisma,
        tenantCache,
        TENANT_ID,
        EMPLOYEE_ID,
        DATE,
        DATE
      )

      expect(ctxMocks.booking.findMany).toHaveBeenCalledTimes(1)
      const call = ctxMocks.booking.findMany.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(call.where).toHaveProperty("tenantId", TENANT_ID)
    })

    it("AUDIT-003: loadTenantCalcCache passes tenantId to holiday.findMany and systemSetting.findFirst", async () => {
      const { prisma, mocks: ctxMocks } = createMockPrisma()

      await loadTenantCalcCache(prisma, TENANT_ID, DATE, DATE)

      expect(ctxMocks.holiday.findMany).toHaveBeenCalledTimes(1)
      const holidayCall = ctxMocks.holiday.findMany.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(holidayCall.where).toHaveProperty("tenantId", TENANT_ID)

      expect(ctxMocks.systemSetting.findFirst).toHaveBeenCalledTimes(1)
      const settingCall = ctxMocks.systemSetting.findFirst.mock.calls[0]![0] as {
        where: Record<string, unknown>
      }
      expect(settingCall.where).toHaveProperty("tenantId", TENANT_ID)
    })
  })

  // ===========================================================================
  // Test 4: Shift detection with tenantId
  // ===========================================================================

  describe("AUDIT-003: shift detection queries include tenantId", () => {
    it("AUDIT-003: dayPlan.findFirst in shift detection includes tenantId when loading matched plan", async () => {
      // Set up a day plan with shift detection enabled
      const shiftDayPlan = makeEmpDayPlan({
        shiftDetectArriveFrom: 360,
        shiftDetectArriveTo: 600,
        shiftDetectDepartFrom: 900,
        shiftDetectDepartTo: 1140,
        shiftAltPlan1: "alt-plan-1",
      })
      mocks.employeeDayPlan.findFirst.mockResolvedValue(shiftDayPlan)

      // Alternative plan for shift detection pre-loading
      mocks.dayPlan.findFirst.mockResolvedValue({
        id: "alt-plan-1",
        tenantId: TENANT_ID,
        code: "ALT",
        shiftDetectArriveFrom: 600,
        shiftDetectArriveTo: 840,
        shiftDetectDepartFrom: 1140,
        shiftDetectDepartTo: 1380,
        shiftAltPlan1: null,
        shiftAltPlan2: null,
        shiftAltPlan3: null,
        shiftAltPlan4: null,
        shiftAltPlan5: null,
        shiftAltPlan6: null,
      })

      // Provide bookings so shift detection runs with real arrival time
      const comeBooking = makeBookingData({
        id: "b-come-shift",
        editedTime: 480,
        bookingType: {
          id: "bt-come",
          tenantId: TENANT_ID,
          code: "COME",
          name: "Come",
          description: null,
          direction: "in",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      const goBooking = makeBookingData({
        id: "b-go-shift",
        editedTime: 960,
        bookingType: {
          id: "bt-go",
          tenantId: TENANT_ID,
          code: "GO",
          name: "Go",
          description: null,
          direction: "out",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      mocks.booking.findMany.mockResolvedValue([comeBooking, goBooking])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // dayPlan.findFirst should have been called for pre-loading alt plans
      expect(mocks.dayPlan.findFirst).toHaveBeenCalled()

      // Verify ALL dayPlan.findFirst calls include tenantId
      for (const call of mocks.dayPlan.findFirst.mock.calls) {
        const args = call[0] as { where: Record<string, unknown> }
        expect(args.where).toHaveProperty("tenantId", TENANT_ID)
      }
    })

    it("AUDIT-003: preloadShiftDetectionPlans passes tenantId for each alternative plan query", async () => {
      // Set up day plan with multiple alternative plans
      const shiftDayPlan = makeEmpDayPlan({
        shiftDetectArriveFrom: 360,
        shiftDetectArriveTo: 600,
        shiftDetectDepartFrom: 900,
        shiftDetectDepartTo: 1140,
        shiftAltPlan1: "alt-1",
        shiftAltPlan2: "alt-2",
        shiftAltPlan3: null,
      })
      mocks.employeeDayPlan.findFirst.mockResolvedValue(shiftDayPlan)

      // Mock returns for each alt plan
      mocks.dayPlan.findFirst
        .mockResolvedValueOnce({
          id: "alt-1",
          code: "ALT1",
          shiftDetectArriveFrom: 600,
          shiftDetectArriveTo: 840,
          shiftDetectDepartFrom: 1140,
          shiftDetectDepartTo: 1380,
          shiftAltPlan1: null,
          shiftAltPlan2: null,
          shiftAltPlan3: null,
          shiftAltPlan4: null,
          shiftAltPlan5: null,
          shiftAltPlan6: null,
        })
        .mockResolvedValueOnce({
          id: "alt-2",
          code: "ALT2",
          shiftDetectArriveFrom: 840,
          shiftDetectArriveTo: 1080,
          shiftDetectDepartFrom: 1380,
          shiftDetectDepartTo: 60,
          shiftAltPlan1: null,
          shiftAltPlan2: null,
          shiftAltPlan3: null,
          shiftAltPlan4: null,
          shiftAltPlan5: null,
          shiftAltPlan6: null,
        })

      const comeBooking = makeBookingData({
        id: "b-c",
        editedTime: 480,
        bookingType: {
          id: "bt-come",
          tenantId: TENANT_ID,
          code: "COME",
          name: "Come",
          description: null,
          direction: "in",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      const goBooking = makeBookingData({
        id: "b-g",
        editedTime: 960,
        bookingType: {
          id: "bt-go",
          tenantId: TENANT_ID,
          code: "GO",
          name: "Go",
          description: null,
          direction: "out",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      mocks.booking.findMany.mockResolvedValue([comeBooking, goBooking])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // Should have loaded 2 alternative plans (alt-1, alt-2)
      // Plus possibly the matched plan if shift was detected
      const findFirstCalls = mocks.dayPlan.findFirst.mock.calls
      expect(findFirstCalls.length).toBeGreaterThanOrEqual(2)

      // All calls must include tenantId
      for (const call of findFirstCalls) {
        const args = call[0] as { where: Record<string, unknown> }
        expect(args.where).toHaveProperty("tenantId", TENANT_ID)
      }
    })

    it("AUDIT-003: dayPlan.findFirst for matched plan reload after shift detection includes tenantId", async () => {
      // Set up a day plan with shift detection that will match a different plan
      const shiftDayPlan = makeEmpDayPlan({
        shiftDetectArriveFrom: 360,
        shiftDetectArriveTo: 540,
        shiftDetectDepartFrom: 900,
        shiftDetectDepartTo: 1080,
        shiftAltPlan1: "alt-plan-match",
      })
      mocks.employeeDayPlan.findFirst.mockResolvedValue(shiftDayPlan)

      // The alt plan has a shift window that matches the bookings better
      const altPlanForCache = {
        id: "alt-plan-match",
        code: "ALT",
        shiftDetectArriveFrom: 540,
        shiftDetectArriveTo: 780,
        shiftDetectDepartFrom: 1080,
        shiftDetectDepartTo: 1320,
        shiftAltPlan1: null,
        shiftAltPlan2: null,
        shiftAltPlan3: null,
        shiftAltPlan4: null,
        shiftAltPlan5: null,
        shiftAltPlan6: null,
      }

      // Full plan data for matched plan reload
      const matchedFullPlan = {
        id: "alt-plan-match",
        tenantId: TENANT_ID,
        code: "ALT",
        name: "Alt Plan",
        regularHours: 480,
        breaks: [],
        bonuses: [],
      }

      // First call: preload alt plans (returns shift detection fields)
      // Second call: reload matched plan (returns full plan with breaks/bonuses)
      mocks.dayPlan.findFirst
        .mockResolvedValueOnce(altPlanForCache)
        .mockResolvedValueOnce(matchedFullPlan)

      // Bookings at 600 arrival (outside original window, inside alt window)
      const comeBooking = makeBookingData({
        id: "b-c2",
        editedTime: 600,
        bookingType: {
          id: "bt-come",
          tenantId: TENANT_ID,
          code: "COME",
          name: "Come",
          description: null,
          direction: "in",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      const goBooking = makeBookingData({
        id: "b-g2",
        editedTime: 1100,
        bookingType: {
          id: "bt-go",
          tenantId: TENANT_ID,
          code: "GO",
          name: "Go",
          description: null,
          direction: "out",
          category: "work",
          accountId: null,
          requiresReason: false,
          isSystem: true,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      })
      mocks.booking.findMany.mockResolvedValue([comeBooking, goBooking])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // All dayPlan.findFirst calls must include tenantId
      for (const call of mocks.dayPlan.findFirst.mock.calls) {
        const args = call[0] as { where: Record<string, unknown> }
        expect(args.where).toHaveProperty("tenantId", TENANT_ID)
      }
    })
  })
})
