/**
 * Tests for DailyCalcService
 *
 * Uses vitest mocking to test the service without a real database.
 */

import { describe, it, expect, vi, beforeEach } from "vitest"
import { DailyCalcService } from "../daily-calc"
import type { PrismaClient } from "@/generated/prisma/client"

// --- Mock Prisma Client ---

function createMockPrisma(): {
  prisma: PrismaClient
  mocks: ReturnType<typeof createPrismaMocks>
} {
  const mocks = createPrismaMocks()
  return { prisma: mocks as unknown as PrismaClient, mocks }
}

function createPrismaMocks() {
  return {
    holiday: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    employeeDayPlan: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    booking: {
      findMany: vi.fn().mockResolvedValue([]),
      create: vi.fn(),
      update: vi.fn(),
    },
    employee: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    dailyValue: {
      findUnique: vi.fn().mockResolvedValue(null),
      upsert: vi.fn().mockImplementation(async (args: { create: Record<string, unknown> }) => ({
        id: "dv-1",
        ...args.create,
      })),
    },
    dailyAccountValue: {
      deleteMany: vi.fn().mockResolvedValue({ count: 0 }),
      upsert: vi.fn().mockResolvedValue({}),
    },
    systemSetting: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    notification: {
      create: vi.fn().mockResolvedValue({}),
    },
    dayPlan: {
      findFirst: vi.fn().mockResolvedValue(null),
    },
    orderBooking: {
      deleteMany: vi.fn().mockResolvedValue({ count: 0 }),
      create: vi.fn().mockResolvedValue({}),
    },
    $queryRaw: vi.fn().mockResolvedValue([]),
    $executeRaw: vi.fn().mockResolvedValue(0),
    $transaction: vi.fn().mockResolvedValue([]),
  }
}

// --- Test Data Factories ---

const TENANT_ID = "t-1"
const EMPLOYEE_ID = "e-1"
const DATE = new Date("2026-03-01T00:00:00Z")

function makeEmpDayPlan(overrides: Record<string, unknown> = {}) {
  return {
    id: "edp-1",
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    planDate: DATE,
    dayPlanId: "dp-1",
    shiftId: null,
    source: "tariff",
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    dayPlan: {
      id: "dp-1",
      tenantId: TENANT_ID,
      code: "STD",
      name: "Standard",
      description: null,
      planType: "fixed",
      comeFrom: 420,
      comeTo: 540,
      goFrom: 960,
      goTo: 1080,
      coreStart: null,
      coreEnd: null,
      regularHours: 480,
      regularHours2: null,
      fromEmployeeMaster: false,
      toleranceComePlus: 15,
      toleranceComeMinus: 15,
      toleranceGoPlus: 15,
      toleranceGoMinus: 15,
      roundingComeType: null,
      roundingComeInterval: null,
      roundingGoType: null,
      roundingGoInterval: null,
      minWorkTime: null,
      maxNetWorkTime: null,
      variableWorkTime: false,
      roundAllBookings: false,
      roundingComeAddValue: null,
      roundingGoAddValue: null,
      holidayCreditCat1: 480,
      holidayCreditCat2: 240,
      holidayCreditCat3: null,
      vacationDeduction: "1.00",
      noBookingBehavior: "error",
      dayChangeBehavior: "none",
      shiftDetectArriveFrom: null,
      shiftDetectArriveTo: null,
      shiftDetectDepartFrom: null,
      shiftDetectDepartTo: null,
      shiftAltPlan1: null,
      shiftAltPlan2: null,
      shiftAltPlan3: null,
      shiftAltPlan4: null,
      shiftAltPlan5: null,
      shiftAltPlan6: null,
      netAccountId: null,
      capAccountId: null,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
      breaks: [],
      bonuses: [],
      ...overrides,
    },
    ...overrides,
  }
}

function makeBookingData(overrides: Record<string, unknown> = {}) {
  return {
    id: "b-1",
    tenantId: TENANT_ID,
    employeeId: EMPLOYEE_ID,
    bookingDate: DATE,
    bookingTypeId: "bt-come",
    originalTime: 480,
    editedTime: 480,
    calculatedTime: null,
    pairId: null,
    source: "web",
    terminalId: null,
    notes: null,
    bookingReasonId: null,
    isAutoGenerated: false,
    originalBookingId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    createdBy: null,
    updatedBy: null,
    bookingType: {
      id: "bt-come",
      tenantId: TENANT_ID,
      code: "COME",
      name: "Come",
      description: null,
      direction: "in",
      category: "work",
      accountId: null,
      requiresReason: false,
      isSystem: true,
      isActive: true,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ...overrides,
  }
}

// --- Tests ---

describe("DailyCalcService", () => {
  let service: DailyCalcService
  let mocks: ReturnType<typeof createPrismaMocks>

  beforeEach(() => {
    const result = createMockPrisma()
    service = new DailyCalcService(result.prisma)
    mocks = result.mocks
  })

  describe("calculateDay", () => {
    it("handles off day (no day plan)", async () => {
      // No day plan returned
      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)

      const result = await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)
      expect(result).not.toBeNull()

      // Check upsert was called with correct values
      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.status).toBe("calculated")
      expect(upsertCall.create.targetTime).toBe(0)
      expect(upsertCall.create.warnings).toContain("OFF_DAY")
    })

    it("handles off day with bookings (warning)", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)
      mocks.booking.findMany.mockResolvedValue([
        makeBookingData(),
      ])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.warnings).toContain("OFF_DAY")
      expect(upsertCall.create.warnings).toContain("BOOKINGS_ON_OFF_DAY")
      expect(upsertCall.create.bookingCount).toBe(1)
    })

    it("handles holiday without bookings (category 1)", async () => {
      mocks.holiday.findFirst.mockResolvedValue({
        id: "h1",
        tenantId: TENANT_ID,
        holidayDate: DATE,
        name: "New Year",
        holidayCategory: 1,
        appliesToAll: true,
        departmentId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      mocks.employeeDayPlan.findFirst.mockResolvedValue(makeEmpDayPlan())
      mocks.booking.findMany.mockResolvedValue([])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.warnings).toContain("HOLIDAY")
      expect(upsertCall.create.netTime).toBe(480) // holidayCreditCat1
      expect(upsertCall.create.grossTime).toBe(480)
      expect(upsertCall.create.targetTime).toBe(480)
      expect(upsertCall.create.undertime).toBe(0)
    })

    it("handles holiday with absence priority override", async () => {
      mocks.holiday.findFirst.mockResolvedValue({
        id: "h1",
        tenantId: TENANT_ID,
        holidayDate: DATE,
        name: "Christmas",
        holidayCategory: 1,
        appliesToAll: true,
        departmentId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      mocks.employeeDayPlan.findFirst.mockResolvedValue(makeEmpDayPlan())
      mocks.booking.findMany.mockResolvedValue([])

      // Return absence with priority > 0
      mocks.$queryRaw.mockResolvedValue([
        {
          id: "ad1",
          status: "approved",
          duration: "1.00",
          at_portion: 2, // half day
          at_priority: 1,
          at_code: "UR",
        },
      ])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.warnings).toContain("ABSENCE_ON_HOLIDAY")
      // Credit = floor(480 * 0.5 * 1.0) = 240
      expect(upsertCall.create.netTime).toBe(240)
      expect(upsertCall.create.grossTime).toBe(240)
      expect(upsertCall.create.undertime).toBe(240) // 480 - 240
    })

    it("handles no bookings - error behavior", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "error" })
      )

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.status).toBe("error")
      expect(upsertCall.create.hasError).toBe(true)
      expect(upsertCall.create.errorCodes).toContain("NO_BOOKINGS")
      expect(upsertCall.create.undertime).toBe(480)
    })

    it("handles no bookings - adopt_target behavior", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "adopt_target" })
      )

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.status).toBe("calculated")
      expect(upsertCall.create.netTime).toBe(480)
      expect(upsertCall.create.grossTime).toBe(480)
      expect(upsertCall.create.targetTime).toBe(480)
      expect(upsertCall.create.warnings).toContain("NO_BOOKINGS_CREDITED")
    })

    it("handles no bookings - deduct_target behavior", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "deduct_target" })
      )

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.netTime).toBe(0)
      expect(upsertCall.create.grossTime).toBe(0)
      expect(upsertCall.create.undertime).toBe(480)
      expect(upsertCall.create.warnings).toContain("NO_BOOKINGS_DEDUCTED")
    })

    it("calculates standard 8h work day", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(makeEmpDayPlan())
      mocks.booking.findMany.mockResolvedValue([
        makeBookingData({
          id: "b-come",
          editedTime: 480,
          bookingType: {
            id: "bt-come",
            tenantId: TENANT_ID,
            code: "COME",
            name: "Come",
            description: null,
            direction: "in",
            category: "work",
            accountId: null,
            requiresReason: false,
            isSystem: true,
            isActive: true,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
        makeBookingData({
          id: "b-go",
          editedTime: 960,
          bookingType: {
            id: "bt-go",
            tenantId: TENANT_ID,
            code: "GO",
            name: "Go",
            description: null,
            direction: "out",
            category: "work",
            accountId: null,
            requiresReason: false,
            isSystem: true,
            isActive: true,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
      ])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.status).toBe("calculated")
      expect(upsertCall.create.grossTime).toBe(480)
      expect(upsertCall.create.targetTime).toBe(480)
      expect(upsertCall.create.overtime).toBe(0)
      expect(upsertCall.create.undertime).toBe(0)
      expect(upsertCall.create.bookingCount).toBe(2)
    })

    it("calculates with overtime", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(makeEmpDayPlan())
      mocks.booking.findMany.mockResolvedValue([
        makeBookingData({
          id: "b-come",
          editedTime: 420,
          bookingType: {
            id: "bt-come",
            tenantId: TENANT_ID,
            code: "COME",
            name: "Come",
            description: null,
            direction: "in",
            category: "work",
            accountId: null,
            requiresReason: false,
            isSystem: true,
            isActive: true,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
        makeBookingData({
          id: "b-go",
          editedTime: 1020,
          bookingType: {
            id: "bt-go",
            tenantId: TENANT_ID,
            code: "GO",
            name: "Go",
            description: null,
            direction: "out",
            category: "work",
            accountId: null,
            requiresReason: false,
            isSystem: true,
            isActive: true,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
      ])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.grossTime).toBe(600)
      expect(upsertCall.create.targetTime).toBe(480)
      expect(upsertCall.create.overtime).toBe(120)
    })

    it("upserts DailyValue correctly", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.dailyValue.upsert).toHaveBeenCalledTimes(1)
      const call = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        where: Record<string, unknown>
        create: Record<string, unknown>
        update: Record<string, unknown>
      }
      expect(call.where).toEqual({
        employeeId_valueDate: {
          employeeId: EMPLOYEE_ID,
          valueDate: DATE,
        },
      })
      expect(call.create.tenantId).toBe(TENANT_ID)
      expect(call.create.employeeId).toBe(EMPLOYEE_ID)
    })

    it("posts net_time account value when configured", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({
          noBookingBehavior: "adopt_target",
          netAccountId: "acc-net",
        })
      )

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.dailyAccountValue.upsert).toHaveBeenCalled()
      const upsertCalls = mocks.dailyAccountValue.upsert.mock.calls
      const netCall = upsertCalls.find(
        (c: unknown[]) => (c[0] as { create: { source: string } }).create.source === "net_time"
      )
      expect(netCall).toBeDefined()
    })

    it("posts capped_time account value when configured", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({
          noBookingBehavior: "adopt_target",
          capAccountId: "acc-cap",
          maxNetWorkTime: 480,
        })
      )

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCalls = mocks.dailyAccountValue.upsert.mock.calls
      const capCall = upsertCalls.find(
        (c: unknown[]) => (c[0] as { create: { source: string } }).create.source === "capped_time"
      )
      expect(capCall).toBeDefined()
    })

    it("notifies on new error detection", async () => {
      // Set up: no bookings (error behavior), no previous value
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "error" })
      )
      mocks.dailyValue.findUnique.mockResolvedValue(null)

      // notifyDailyCalcError calls employee.findFirst to check if employee exists
      mocks.employee.findFirst.mockResolvedValue({ id: EMPLOYEE_ID })

      // Mock $queryRaw calls in order:
      // 1. loadAbsenceDay (from resolveTargetHours in handleNoBookings)
      // 2. loadAbsenceDay (from step 7.5 postAbsenceRuleValue)
      // 3. user_tenants lookup (from notifyDailyCalcError)
      mocks.$queryRaw
        .mockResolvedValueOnce([]) // absence_days query (resolveTargetHours)
        .mockResolvedValueOnce([]) // absence_days query (step 7.5)
        .mockResolvedValueOnce([{ user_id: "u-1" }]) // user_tenants query

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.notification.create).toHaveBeenCalled()
    })

    it("does not notify when previous had error", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "error" })
      )
      // Previous value already had error
      mocks.dailyValue.findUnique.mockResolvedValue({ hasError: true })

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      expect(mocks.notification.create).not.toHaveBeenCalled()
    })

    it("adds WORKED_ON_HOLIDAY warning when bookings exist on holiday", async () => {
      mocks.holiday.findFirst.mockResolvedValue({
        id: "h1",
        tenantId: TENANT_ID,
        holidayDate: DATE,
        name: "Holiday",
        holidayCategory: 1,
        appliesToAll: true,
        departmentId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      })
      mocks.employeeDayPlan.findFirst.mockResolvedValue(makeEmpDayPlan())
      mocks.booking.findMany.mockResolvedValue([
        makeBookingData({
          id: "b-come",
          editedTime: 480,
          bookingType: {
            id: "bt-come",
            tenantId: TENANT_ID,
            code: "COME",
            name: "Come",
            description: null,
            direction: "in",
            category: "work",
            accountId: null,
            requiresReason: false,
            isSystem: true,
            isActive: true,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
        makeBookingData({
          id: "b-go",
          editedTime: 960,
          bookingType: {
            id: "bt-go",
            tenantId: TENANT_ID,
            code: "GO",
            name: "Go",
            description: null,
            direction: "out",
            category: "work",
            accountId: null,
            requiresReason: false,
            isSystem: true,
            isActive: true,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
      ])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCall = mocks.dailyValue.upsert.mock.calls[0]![0] as {
        create: Record<string, unknown>
      }
      expect(upsertCall.create.warnings).toContain("WORKED_ON_HOLIDAY")
    })

    it("posts absence_rule account value when absence has calculation rule", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "adopt_target" })
      )

      // Mock loadAbsenceDay ($queryRaw) to return absence with calculation rule
      const absenceRow = {
        id: "ad1",
        status: "approved",
        duration: "1.00",
        at_portion: 1,
        at_priority: 0,
        at_code: "K01",
        cr_account_id: "acc-sick",
        cr_value: 0,
        cr_factor: "1.00",
      }
      mocks.$queryRaw.mockResolvedValue([absenceRow])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCalls = mocks.dailyAccountValue.upsert.mock.calls
      const absenceRuleCall = upsertCalls.find(
        (c: unknown[]) => (c[0] as { create: { source: string } }).create.source === "absence_rule"
      )
      expect(absenceRuleCall).toBeDefined()
      const create = (absenceRuleCall![0] as { create: Record<string, unknown> }).create
      expect(create.accountId).toBe("acc-sick")
      expect(create.valueMinutes).toBe(480) // targetTime * 1.0
    })

    it("does not post absence_rule when no calculation rule linked", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "adopt_target" })
      )

      mocks.$queryRaw.mockResolvedValue([{
        id: "ad1",
        status: "approved",
        duration: "1.00",
        at_portion: 1,
        at_priority: 0,
        at_code: "U01",
        cr_account_id: null,
        cr_value: null,
        cr_factor: null,
      }])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCalls = mocks.dailyAccountValue.upsert.mock.calls
      const absenceRuleCall = upsertCalls.find(
        (c: unknown[]) => (c[0] as { create: { source: string } }).create.source === "absence_rule"
      )
      expect(absenceRuleCall).toBeUndefined()
    })

    it("cleans up absence_rule posting when no absence", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "adopt_target" })
      )

      mocks.$queryRaw.mockResolvedValue([])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const deleteCalls = mocks.dailyAccountValue.deleteMany.mock.calls
      const absenceRuleDelete = deleteCalls.find(
        (c: unknown[]) => (c[0] as { where: { source?: string } }).where.source === "absence_rule"
      )
      expect(absenceRuleDelete).toBeDefined()
    })

    it("uses fixed ruleValue when > 0 (ignores targetTime)", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(
        makeEmpDayPlan({ noBookingBehavior: "adopt_target" })
      )

      mocks.$queryRaw.mockResolvedValue([{
        id: "ad1",
        status: "approved",
        duration: "1.00",
        at_portion: 1,
        at_priority: 0,
        at_code: "K01",
        cr_account_id: "acc-sick",
        cr_value: 120,
        cr_factor: "1.50",
      }])

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      const upsertCalls = mocks.dailyAccountValue.upsert.mock.calls
      const absenceRuleCall = upsertCalls.find(
        (c: unknown[]) => (c[0] as { create: { source: string } }).create.source === "absence_rule"
      )
      expect(absenceRuleCall).toBeDefined()
      const create = (absenceRuleCall![0] as { create: Record<string, unknown> }).create
      expect(create.valueMinutes).toBe(180) // 120 * 1.5
    })

    it("cleans up account postings when no day plan", async () => {
      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)

      await service.calculateDay(TENANT_ID, EMPLOYEE_ID, DATE)

      // Should delete all account values for this date
      expect(mocks.dailyAccountValue.deleteMany).toHaveBeenCalledWith({
        where: { employeeId: EMPLOYEE_ID, valueDate: DATE },
      })
    })
  })

  describe("calculateDateRange", () => {
    it("calculates 3 days sequentially", async () => {
      const from = new Date("2026-03-01T00:00:00Z")
      const to = new Date("2026-03-03T00:00:00Z")

      // No day plan for any day -> all off days
      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)

      const { count, values } = await service.calculateDateRange(
        TENANT_ID,
        EMPLOYEE_ID,
        from,
        to
      )

      expect(count).toBe(3)
      expect(values.length).toBe(3)
      expect(mocks.dailyValue.upsert).toHaveBeenCalledTimes(3)
    })

    it("returns count and values", async () => {
      const from = new Date("2026-03-01T00:00:00Z")
      const to = new Date("2026-03-01T00:00:00Z")

      mocks.employeeDayPlan.findFirst.mockResolvedValue(null)

      const { count, values } = await service.calculateDateRange(
        TENANT_ID,
        EMPLOYEE_ID,
        from,
        to
      )

      expect(count).toBe(1)
      expect(values.length).toBe(1)
    })
  })
})
