/**
 * Bookings Repository
 *
 * Pure Prisma data-access functions for the Booking model.
 * Handles all database queries including list with filters,
 * CRUD operations, derived booking management, and transactional deletes.
 */
import type { PrismaClient } from "@/generated/prisma/client"

// --- Prisma Include Objects ---

const bookingListInclude = {
  bookingType: {
    select: { id: true, code: true, name: true, direction: true },
  },
  bookingReason: {
    select: { id: true, code: true, label: true },
  },
  employee: {
    select: {
      id: true,
      personnelNumber: true,
      firstName: true,
      lastName: true,
      departmentId: true,
    },
  },
} as const

const bookingDetailInclude = {
  ...bookingListInclude,
} as const

// --- Data Scope Types ---

export interface DataScopeFilter {
  type: "all" | "tenant" | "department" | "employee"
  departmentIds: string[]
  employeeIds: string[]
}

// --- Repository Functions ---

export async function findMany(
  prisma: PrismaClient,
  tenantId: string,
  params: {
    page: number
    pageSize: number
    employeeId?: string
    fromDate?: string
    toDate?: string
    bookingTypeId?: string
    source?: string
    dataScope: DataScopeFilter
  }
) {
  const where = buildListWhere(tenantId, params)

  const [items, total] = await Promise.all([
    prisma.booking.findMany({
      where,
      include: bookingListInclude,
      skip: (params.page - 1) * params.pageSize,
      take: params.pageSize,
      orderBy: [{ bookingDate: "desc" }, { editedTime: "desc" }],
    }),
    prisma.booking.count({ where }),
  ])

  return { items, total }
}

export async function findById(
  prisma: PrismaClient,
  tenantId: string,
  id: string
) {
  return prisma.booking.findFirst({
    where: { id, tenantId },
    include: bookingDetailInclude,
  })
}

export async function findByIdWithEmployee(
  prisma: PrismaClient,
  tenantId: string,
  id: string
) {
  return prisma.booking.findFirst({
    where: { id, tenantId },
    include: { employee: { select: { id: true, departmentId: true } } },
  })
}

export async function findEmployeeById(
  prisma: PrismaClient,
  tenantId: string,
  employeeId: string
) {
  return prisma.employee.findFirst({
    where: { id: employeeId, tenantId },
  })
}

export async function findBookingType(
  prisma: PrismaClient,
  tenantId: string,
  bookingTypeId: string
) {
  return prisma.bookingType.findFirst({
    where: {
      id: bookingTypeId,
      OR: [{ tenantId }, { tenantId: null }],
      isActive: true,
    },
  })
}

export async function findBookingReason(
  prisma: PrismaClient,
  tenantId: string,
  bookingReasonId: string
) {
  return prisma.bookingReason.findFirst({
    where: { id: bookingReasonId, tenantId },
  })
}

export async function create(
  prisma: PrismaClient,
  data: {
    tenantId: string
    employeeId: string
    bookingDate: Date
    bookingTypeId: string
    originalTime: number
    editedTime: number
    source: string
    notes: string | null
    bookingReasonId: string | null
    createdBy: string | null
    updatedBy: string | null
  }
) {
  return prisma.booking.create({
    data,
    include: bookingDetailInclude,
  })
}

export async function update(
  prisma: PrismaClient,
  tenantId: string,
  id: string,
  data: Record<string, unknown>
) {
  return prisma.booking.update({
    where: { id },
    data,
    include: bookingDetailInclude,
  })
}

export async function deleteWithDerived(
  prisma: PrismaClient,
  tenantId: string,
  id: string
) {
  await prisma.$transaction(async (tx) => {
    // Delete any derived bookings pointing to this one (scoped by tenant)
    await tx.booking.deleteMany({
      where: { originalBookingId: id, tenantId },
    })
    // Delete the booking itself (scoped by tenant)
    const { count } = await tx.booking.deleteMany({
      where: { id, tenantId },
    })
    if (count === 0) {
      throw new Error("Booking not found")
    }
  })
}

// --- Derived Booking Queries ---

export async function findDerivedByOriginalId(
  prisma: PrismaClient,
  tenantId: string,
  originalBookingId: string
) {
  return prisma.booking.findFirst({
    where: { tenantId, originalBookingId },
  })
}

export async function createDerived(
  prisma: PrismaClient,
  data: {
    tenantId: string
    employeeId: string
    bookingDate: Date
    bookingTypeId: string
    originalTime: number
    editedTime: number
    source: string
    isAutoGenerated: boolean
    originalBookingId: string
    bookingReasonId: string | null
    notes: string
    createdBy: string | null
    updatedBy: string | null
  }
) {
  return prisma.booking.create({ data })
}

export async function updateDerived(
  prisma: PrismaClient,
  tenantId: string,
  id: string,
  data: {
    editedTime: number
    originalTime: number
    bookingTypeId: string
    calculatedTime: null
  }
) {
  await prisma.booking.updateMany({
    where: { id, tenantId },
    data,
  })
}

// --- Employee Day Plan Queries (for derived booking reference time) ---

export async function findEmployeeDayPlan(
  prisma: PrismaClient,
  employeeId: string,
  planDate: Date
) {
  return prisma.employeeDayPlan.findFirst({
    where: { employeeId, planDate },
    include: { dayPlan: true },
  })
}

// --- Internal Helpers ---

function buildListWhere(
  tenantId: string,
  params: {
    employeeId?: string
    fromDate?: string
    toDate?: string
    bookingTypeId?: string
    source?: string
    dataScope: DataScopeFilter
  }
): Record<string, unknown> {
  const where: Record<string, unknown> = { tenantId }

  if (params.employeeId) {
    where.employeeId = params.employeeId
  }

  if (params.fromDate || params.toDate) {
    const bookingDate: Record<string, unknown> = {}
    if (params.fromDate) {
      bookingDate.gte = new Date(params.fromDate)
    }
    if (params.toDate) {
      bookingDate.lte = new Date(params.toDate)
    }
    where.bookingDate = bookingDate
  }

  if (params.bookingTypeId) {
    where.bookingTypeId = params.bookingTypeId
  }

  if (params.source) {
    where.source = params.source
  }

  // Apply data scope filtering
  const scopeWhere = buildDataScopeWhere(params.dataScope)
  if (scopeWhere) {
    Object.assign(where, scopeWhere)
  }

  return where
}

function buildDataScopeWhere(
  dataScope: DataScopeFilter
): Record<string, unknown> | null {
  if (dataScope.type === "department") {
    return { employee: { departmentId: { in: dataScope.departmentIds } } }
  } else if (dataScope.type === "employee") {
    return { employeeId: { in: dataScope.employeeIds } }
  }
  return null
}
