/**
 * Platform subscription auto-finalize service (Phase 10a).
 *
 * Transitions DRAFT BillingDocuments generated by the daily recurring-
 * invoices cron to PRINTED status for platform-linked subscriptions. Runs
 * from a separate cron at /api/cron/platform-subscription-autofinalize
 * scheduled 15 minutes after the main recurring-invoices cron.
 *
 * Detection strategy (no FK from BillingDocument back to
 * BillingRecurringInvoice):
 *
 *   1. Load platform_subscriptions with a linked billing_recurring_invoice_id.
 *   2. Read BillingRecurringInvoice.lastGeneratedAt directly via Prisma.
 *      If it's >= today 00:00 UTC, the main cron generated an invoice today.
 *   3. Find the DRAFT BillingDocument in the operator tenant whose
 *      internalNotes contains the subscription marker.
 *   4. If its id does not already equal the subscription's
 *      lastGeneratedInvoiceId, finalize it via the existing Terp service.
 *   5. Update the subscription's lastGeneratedInvoiceId pointer.
 *
 * All writes to Terp tables (step 4) go through the existing Terp service.
 * Direct Prisma access to Terp tables is read-only.
 */
import type { PrismaClient } from "@/generated/prisma/client"
import { PLATFORM_SYSTEM_USER_ID } from "@/trpc/init"
import { serverEnv } from "@/lib/config"
import * as billingDocService from "@/lib/services/billing-document-service"
import * as platformAudit from "@/lib/platform/audit-service"
import * as subscriptionService from "./subscription-service"
import { platformSubscriptionMarker } from "./subscription-service"

export interface AutoFinalizeSummary {
  operatorTenantId: string | null
  scanned: number
  finalized: number
  finalizeFailed: number
  subscriptionPointersUpdated: number
  skippedAlreadyFinalized: number
  skippedSharedDocAlreadyFinalizedThisRun: number
  skippedNoDraftFound: number
  skippedNotDueToday: number
  endedSubscriptions: number
  errors: Array<{ subscriptionId?: string; invoiceId?: string; error: string }>
}

export async function autofinalizePending(
  prisma: PrismaClient,
  now: Date = new Date(),
): Promise<AutoFinalizeSummary> {
  const summary: AutoFinalizeSummary = {
    operatorTenantId: null,
    scanned: 0,
    finalized: 0,
    finalizeFailed: 0,
    subscriptionPointersUpdated: 0,
    skippedAlreadyFinalized: 0,
    skippedSharedDocAlreadyFinalizedThisRun: 0,
    skippedNoDraftFound: 0,
    skippedNotDueToday: 0,
    endedSubscriptions: 0,
    errors: [],
  }

  if (!serverEnv.platformOperatorTenantId) {
    return summary
  }
  const operatorTenantId = serverEnv.platformOperatorTenantId
  summary.operatorTenantId = operatorTenantId

  const todayStart = new Date(
    Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 0, 0, 0, 0),
  )

  // Filter to active subscriptions only. Cancelled subscriptions either
  // (Path A) have their recurring invoice's endDate set — zero future
  // DRAFTs produced — or (Path B) have had their marker removed, so a
  // marker query would find nothing.
  const subs = await prisma.platformSubscription.findMany({
    where: {
      status: "active",
      billingRecurringInvoiceId: { not: null },
    },
    select: {
      id: true,
      billingRecurringInvoiceId: true,
      lastGeneratedInvoiceId: true,
    },
  })
  summary.scanned = subs.length

  // Shared-doc idempotency guard: multiple subscriptions can resolve to the
  // SAME DRAFT document. We must call finalize() exactly once per document
  // in a given run.
  const finalizedThisRun = new Set<string>()

  for (const sub of subs) {
    if (!sub.billingRecurringInvoiceId) continue

    try {
      const recurring = await prisma.billingRecurringInvoice.findFirst({
        where: {
          id: sub.billingRecurringInvoiceId,
          tenantId: operatorTenantId,
        },
        select: { lastGeneratedAt: true },
      })
      if (!recurring?.lastGeneratedAt || recurring.lastGeneratedAt < todayStart) {
        summary.skippedNotDueToday++
        continue
      }

      // Find the most recent BillingDocument matching this subscription's
      // marker — ANY status. We cannot filter `status = DRAFT` in the
      // query: when two subs share the same DRAFT, the FIRST sub's
      // finalize() flips the document to PRINTED mid-loop, so a DRAFT-only
      // query would return null for subsequent siblings in the same run.
      // Instead we match by marker and branch on status below.
      const marker = platformSubscriptionMarker(sub.id)
      const docByMarker = await prisma.billingDocument.findFirst({
        where: {
          tenantId: operatorTenantId,
          type: "INVOICE",
          internalNotes: { contains: marker },
        },
        orderBy: { createdAt: "desc" },
        select: { id: true, status: true },
      })
      if (!docByMarker) {
        summary.skippedNoDraftFound++
        console.warn(
          `[subscription-autofinalize] No invoice found for subscription ${sub.id} ` +
            `(operator tenant ${operatorTenantId}, recurring template ${sub.billingRecurringInvoiceId}). ` +
            `Expected marker in internalNotes: "${marker}". ` +
            `The marker may have been overwritten in the tenant-side billing UI. ` +
            `The operator must manually finalize any stranded DRAFT invoices for this customer.`,
        )
        continue
      }

      // Already pointed at this document — nothing new to do.
      if (docByMarker.id === sub.lastGeneratedInvoiceId) {
        summary.skippedAlreadyFinalized++
        continue
      }

      // Branch on status:
      //   DRAFT  → finalize it now + track in finalizedThisRun
      //   other  → already finalized. If finalizedThisRun has the id, a
      //            sibling did it this run. Otherwise a prior run finalized
      //            it but failed to update THIS sub's pointer; recover by
      //            updating the pointer.
      let sharedDocLabel: "finalized-this-run" | "already-finalized-this-run"
      if (docByMarker.status === "DRAFT") {
        await billingDocService.finalize(
          prisma,
          operatorTenantId,
          docByMarker.id,
          PLATFORM_SYSTEM_USER_ID,
        )
        finalizedThisRun.add(docByMarker.id)
        summary.finalized++
        sharedDocLabel = "finalized-this-run"
      } else if (finalizedThisRun.has(docByMarker.id)) {
        summary.skippedSharedDocAlreadyFinalizedThisRun++
        sharedDocLabel = "already-finalized-this-run"
      } else {
        // Not DRAFT and not finalized-this-run: recover from a prior-run
        // partial failure by just updating the pointer.
        summary.skippedAlreadyFinalized++
        sharedDocLabel = "already-finalized-this-run"
      }

      await prisma.platformSubscription.update({
        where: { id: sub.id },
        data: { lastGeneratedInvoiceId: docByMarker.id },
      })
      summary.subscriptionPointersUpdated++

      await platformAudit.log(prisma, {
        platformUserId: null,
        action: "subscription.invoice_auto_finalized",
        entityType: "billing_document",
        entityId: docByMarker.id,
        targetTenantId: operatorTenantId,
        metadata: {
          subscriptionId: sub.id,
          recurringInvoiceId: sub.billingRecurringInvoiceId,
          sharedDoc: sharedDocLabel,
        },
      })
    } catch (err) {
      summary.finalizeFailed++
      summary.errors.push({
        subscriptionId: sub.id,
        error: err instanceof Error ? err.message : String(err),
      })
      console.error(
        `[subscription-autofinalize] Failed for subscription ${sub.id}:`,
        err,
      )
    }
  }

  summary.endedSubscriptions = await subscriptionService
    .sweepEndedSubscriptions(prisma)
    .catch((err) => {
      summary.errors.push({ error: `sweepEnded failed: ${String(err)}` })
      return 0
    })

  return summary
}
